#!/usr/bin/env python3
"""AEGIS Ω CUDA-Q coupled two-qubit Hamiltonian benchmark.

Computational scope only:

    H = J Z0 Z1 + h0 Z0 + h1 Z1
    J  = 0.7
    h0 = 0.2
    h1 = -0.1

The four computational basis states are exact eigenstates. For |++> and the
commuting evolution generated by H,

    <X0>(t) = cos(2 h0 t) cos(2 J t)
    <X1>(t) = cos(2 h1 t) cos(2 J t)

CUDA-Q is used only as an independent simulator cross-check. This module does
not consume empirical data and grants no physics or operational authority.
"""
from __future__ import annotations

import importlib.metadata
import json
import math

import cudaq
from cudaq import spin

SCHEMA = "AEGIS_CUDAQ_COUPLED_TWO_QUBIT_HAMILTONIAN_V1"
COEFFICIENT_SCALE = 1_000_000
TIME_SCALE = 1_000_000
VALUE_SCALE = 1_000_000_000_000
SPECTRUM_TOLERANCE_SCALED = 1_000
DYNAMICS_TOLERANCE_SCALED = 1_000

INTERACTION_J_SCALED = 700_000
FIELD0_SCALED = 200_000
FIELD1_SCALED = -100_000
DEFAULT_TIME_SCALED = (0, 250_000, 500_000, 750_000, 1_000_000)

PARENT_PHASE_HEAD = "fd297154264455c055ee40b10eed44f86e23edf6"
PARENT_PHASE_RECEIPT_SHA256 = "24ccf846dafbbb34ecb5471703c440a4c41f5030cb637302d5c4b80460ac1d01"

cudaq.set_target("qpp-cpu")


@cudaq.kernel
def _basis_00():
    q = cudaq.qvector(2)


@cudaq.kernel
def _basis_01():
    q = cudaq.qvector(2)
    x(q[1])


@cudaq.kernel
def _basis_10():
    q = cudaq.qvector(2)
    x(q[0])


@cudaq.kernel
def _basis_11():
    q = cudaq.qvector(2)
    x(q[0])
    x(q[1])


@cudaq.kernel
def _evolved_plus_plus(phi0: float, phi1: float, phizz: float):
    q = cudaq.qvector(2)
    h(q[0])
    h(q[1])
    rz(phi0, q[0])
    rz(phi1, q[1])
    x.ctrl(q[0], q[1])
    rz(phizz, q[1])
    x.ctrl(q[0], q[1])


_BASIS_KERNELS = {
    "00": _basis_00,
    "01": _basis_01,
    "10": _basis_10,
    "11": _basis_11,
}


def _scaled_to_float(value: int, scale: int) -> float:
    return value / float(scale)


def _to_value_scale(value: float) -> int:
    return int(round(value * VALUE_SCALE))


def _require_time_scaled(time_scaled: int) -> int:
    if type(time_scaled) is not int:
        raise ValueError("TIME_SCALED_MUST_BE_INTEGER")
    return time_scaled


def _hamiltonian():
    j = _scaled_to_float(INTERACTION_J_SCALED, COEFFICIENT_SCALE)
    h0 = _scaled_to_float(FIELD0_SCALED, COEFFICIENT_SCALE)
    h1 = _scaled_to_float(FIELD1_SCALED, COEFFICIENT_SCALE)
    return (
        j * (spin.z(0) * spin.z(1))
        + h0 * spin.z(0)
        + h1 * spin.z(1)
    )


def analytic_spectrum_scaled() -> dict:
    coefficient_to_value = VALUE_SCALE // COEFFICIENT_SCALE
    by_basis = {}
    for basis in ("00", "01", "10", "11"):
        z0 = 1 if basis[0] == "0" else -1
        z1 = 1 if basis[1] == "0" else -1
        energy_coefficient_scaled = (
            INTERACTION_J_SCALED * z0 * z1
            + FIELD0_SCALED * z0
            + FIELD1_SCALED * z1
        )
        by_basis[basis] = energy_coefficient_scaled * coefficient_to_value
    return {
        "by_basis": by_basis,
        "sorted": sorted(by_basis.values()),
    }


def cudaq_spectrum_scaled() -> dict:
    hamiltonian = _hamiltonian()
    observed = {}
    for basis, kernel in _BASIS_KERNELS.items():
        expectation = cudaq.observe(kernel, hamiltonian).expectation()
        observed[basis] = _to_value_scale(expectation)
    return observed


def _classical_dynamics_scaled(time_scaled: int) -> tuple[int, int]:
    time_scaled = _require_time_scaled(time_scaled)
    t = _scaled_to_float(time_scaled, TIME_SCALE)
    j = _scaled_to_float(INTERACTION_J_SCALED, COEFFICIENT_SCALE)
    h0 = _scaled_to_float(FIELD0_SCALED, COEFFICIENT_SCALE)
    h1 = _scaled_to_float(FIELD1_SCALED, COEFFICIENT_SCALE)
    x0 = math.cos(2.0 * h0 * t) * math.cos(2.0 * j * t)
    x1 = math.cos(2.0 * h1 * t) * math.cos(2.0 * j * t)
    return _to_value_scale(x0), _to_value_scale(x1)


def run_dynamics_point(time_scaled: int) -> dict:
    time_scaled = _require_time_scaled(time_scaled)
    t = _scaled_to_float(time_scaled, TIME_SCALE)
    j = _scaled_to_float(INTERACTION_J_SCALED, COEFFICIENT_SCALE)
    h0 = _scaled_to_float(FIELD0_SCALED, COEFFICIENT_SCALE)
    h1 = _scaled_to_float(FIELD1_SCALED, COEFFICIENT_SCALE)

    phi0 = 2.0 * h0 * t
    phi1 = 2.0 * h1 * t
    phizz = 2.0 * j * t

    classical_x0, classical_x1 = _classical_dynamics_scaled(time_scaled)
    cudaq_x0 = _to_value_scale(
        cudaq.observe(_evolved_plus_plus, spin.x(0), phi0, phi1, phizz).expectation()
    )
    cudaq_x1 = _to_value_scale(
        cudaq.observe(_evolved_plus_plus, spin.x(1), phi0, phi1, phizz).expectation()
    )
    error_x0 = abs(cudaq_x0 - classical_x0)
    error_x1 = abs(cudaq_x1 - classical_x1)

    return {
        "time_scaled": time_scaled,
        "classical_x0_scaled": classical_x0,
        "cudaq_x0_scaled": cudaq_x0,
        "abs_error_x0_scaled": error_x0,
        "classical_x1_scaled": classical_x1,
        "cudaq_x1_scaled": cudaq_x1,
        "abs_error_x1_scaled": error_x1,
        "tolerance_scaled": DYNAMICS_TOLERANCE_SCALED,
        "within_tolerance": (
            error_x0 <= DYNAMICS_TOLERANCE_SCALED
            and error_x1 <= DYNAMICS_TOLERANCE_SCALED
        ),
    }


def build_twoqubit_receipt() -> dict:
    analytic = analytic_spectrum_scaled()
    observed = cudaq_spectrum_scaled()
    spectrum_errors = {
        basis: abs(observed[basis] - analytic["by_basis"][basis])
        for basis in analytic["by_basis"]
    }
    spectrum_ok = all(
        error <= SPECTRUM_TOLERANCE_SCALED for error in spectrum_errors.values()
    )

    dynamics = [run_dynamics_point(t) for t in DEFAULT_TIME_SCALED]
    dynamics_ok = all(point["within_tolerance"] for point in dynamics)

    if not spectrum_ok:
        raise ValueError("CUDAQ_TWO_QUBIT_SPECTRUM_OUTSIDE_TOLERANCE")
    if not dynamics_ok:
        raise ValueError("CUDAQ_TWO_QUBIT_DYNAMICS_OUTSIDE_TOLERANCE")

    return {
        "schema": SCHEMA,
        "scope": "RESEARCH_ONLY_COMPUTATIONAL_CROSSCHECK",
        "parent_phase_head": PARENT_PHASE_HEAD,
        "parent_phase_receipt_sha256": PARENT_PHASE_RECEIPT_SHA256,
        "cudaq_version": importlib.metadata.version("cudaq"),
        "target": "qpp-cpu",
        "hamiltonian": "H=0.7*Z0Z1+0.2*Z0-0.1*Z1",
        "hamiltonian_family": "COMMUTING_COUPLED_TWO_QUBIT_ISING",
        "coefficient_scale": COEFFICIENT_SCALE,
        "parameters_scaled": {
            "interaction_j": INTERACTION_J_SCALED,
            "field_0": FIELD0_SCALED,
            "field_1": FIELD1_SCALED,
        },
        "basis_order": ["00", "01", "10", "11"],
        "analytic_spectrum_scaled": analytic,
        "cudaq_spectrum_scaled": observed,
        "spectrum_abs_error_scaled": spectrum_errors,
        "spectrum_tolerance_scaled": SPECTRUM_TOLERANCE_SCALED,
        "spectrum_status": "VERIFIED_IN_DECLARED_COMPUTATIONAL_SCOPE",
        "initial_state": "|++>",
        "evolution_decomposition": "RZ(2*h0*t) RZ(2*h1*t) CNOT RZ(2*J*t) CNOT",
        "classical_dynamics_oracle": {
            "x0": "cos(2*h0*t)*cos(2*J*t)",
            "x1": "cos(2*h1*t)*cos(2*J*t)",
        },
        "time_scale": TIME_SCALE,
        "value_scale": VALUE_SCALE,
        "dynamics_tolerance_scaled": DYNAMICS_TOLERANCE_SCALED,
        "dynamics": dynamics,
        "dynamics_status": "VERIFIED_IN_DECLARED_COMPUTATIONAL_SCOPE",
        "shots_count": "ANALYTIC_OBSERVE_NO_SHOTS",
        "checks": {
            "all_four_eigenvalues_within_tolerance": spectrum_ok,
            "all_dynamics_points_within_tolerance": dynamics_ok,
            "analytic_spectrum_non_degenerate": len(set(analytic["sorted"])) == 4,
            "integer_scaled_receipt": True,
        },
        "gpu_acceleration_tested": False,
        "qpu_hardware_tested": False,
        "empirical_data_used": False,
        "quantum_gravity_status": "NOT_TESTED",
        "physics_claim_effect": "NONE",
        "authority_effect": "NONE",
    }


if __name__ == "__main__":
    print(json.dumps(build_twoqubit_receipt(), indent=2, sort_keys=True))
