"""Versioned projection hooks — RFC 0005 §5.

Given two IR versions and a record present in both, emit version-tagged target
artefacts: a Rust enum dispatching between ``NameV1`` / ``NameV2`` structs, and
TypeScript ``V1`` / ``V2`` interfaces with a structural compatibility assertion
derived from the evolution verdict (§2).

Boundary note: RFC 0005 §5.1/§5.2 specify Canonical-ABI byte-offset dispatch
(``#[repr(C)]``, ``offset_of!`` proofs, ``DataView`` offsets). Those rest on
the Stage 3 ABI layout (RFC 0003), which is not implemented. This module emits
*structural* version dispatch and *type-level* compatibility assertions only —
correct on the Stage 1 foundation, with no fabricated byte offsets.
"""

from __future__ import annotations

from .evolution import (
    VERDICT_BACKWARD,
    VERDICT_BREAKING,
    VERDICT_FORWARD,
    VERDICT_FULL,
    classify,
    diff,
)
from .ir import IR, IRRecord, IRType
from .projections import range_comment_text, snake_to_pascal
from .projections.rust import _DERIVE, _rust_type
from .projections.typescript import _ts_type


def _find_record(ir: IR, name: str) -> IRRecord:
    for r in ir.records:
        if r.name == name:
            return r
    raise ValueError(f"record {name!r} not found in schema")


def _collect_refs(t: IRType, acc: set) -> None:
    if t.kind == "ref":
        acc.add(t.name)
    elif t.kind in ("list", "option"):
        _collect_refs(t.inner, acc)


def _record_lookup(new: IR, old: IR) -> dict:
    d = {r.name: r for r in old.records}
    d.update({r.name: r for r in new.records})  # new takes precedence for shared types
    return d


def _variant_lookup(new: IR, old: IR) -> dict:
    d = {v.name: v for v in old.variants}
    d.update({v.name: v for v in new.variants})
    return d


def _referenced_types(records: list[IRRecord], record_lookup: dict, exclude: str) -> set:
    """Transitive closure of type names referenced by the given records. The
    lookup must span both schema versions so types that exist only in the old
    version (referenced by the V1 struct) are still emitted."""
    acc: set = set()
    for rec in records:
        for f in rec.fields:
            _collect_refs(f.type, acc)
    changed = True
    while changed:
        changed = False
        for name in list(acc):
            r = record_lookup.get(name)
            if r:
                for f in r.fields:
                    before = len(acc)
                    _collect_refs(f.type, acc)
                    changed = changed or len(acc) > before
    acc.discard(exclude)
    return acc


def _rust_struct(name: str, rec: IRRecord) -> list[str]:
    lines = ["#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]", f"pub struct {name} {{"]
    for f in rec.fields:
        if f.range is not None:
            lines.append(f"    /// {range_comment_text(f.range.min, f.range.max)}")
        lines.append(f"    pub {f.name}: {_rust_type(f.type)},")
    lines.append("}")
    return lines


def render_rust(old: IR, new: IR, type_name: str) -> str:
    old_rec = _find_record(old, type_name)
    new_rec = _find_record(new, type_name)
    rec_lookup = _record_lookup(new, old)
    var_lookup = _variant_lookup(new, old)
    refs = _referenced_types([old_rec, new_rec], rec_lookup, type_name)
    lines = [
        "// AUTO-GENERATED by aegis-interface (RFC 0005 §5.1). DO NOT EDIT.",
        "// Version-tagged structural dispatch. ABI byte-offset dispatch is Stage 3 (RFC 0003).",
        "",
        "use serde::{Deserialize, Serialize};",
        "",
    ]
    for name in sorted(n for n in refs if n in var_lookup):
        v = var_lookup[name]
        lines.append(_DERIVE)
        lines.append('#[serde(rename_all = "snake_case")]')
        lines.append(f"pub enum {v.name} {{")
        for c in v.cases:
            lines.append(f"    {snake_to_pascal(c)},")
        lines.append("}")
        lines.append("")
    for name in sorted(n for n in refs if n in rec_lookup):
        lines += _rust_struct(name, rec_lookup[name])
        lines.append("")
    lines += _rust_struct(f"{type_name}V1", old_rec)
    lines.append("")
    lines += _rust_struct(f"{type_name}V2", new_rec)
    lines.append("")
    lines.append("#[repr(u32)]")
    lines.append("#[derive(Debug, Clone, PartialEq)]")
    lines.append(f"pub enum Evolved{type_name} {{")
    lines.append(f"    V1({type_name}V1) = 1,")
    lines.append(f"    V2({type_name}V2) = 2,")
    lines.append("}")
    lines.append("")
    lines += _migration_section(old_rec, new_rec, type_name)
    return "\n".join(lines).rstrip("\n") + "\n"


def _migration_section(old_rec: IRRecord, new_rec: IRRecord, type_name: str) -> list[str]:
    """Upgrade/Downgrade scaffolds derived from the field-level Δ (RFC 0005 §5).

    Fields carried unchanged are mapped directly; added required fields and
    retypes are emitted as ``todo!`` obligations (no value can be synthesised);
    fields dropped on downgrade are recorded in a LossReport.
    """
    old_t = {f.name: _rust_type(f.type) for f in old_rec.fields}
    new_t = {f.name: _rust_type(f.type) for f in new_rec.fields}
    new_optional = {f.name for f in new_rec.fields if f.type.kind == "option"}

    v1, v2 = f"{type_name}V1", f"{type_name}V2"
    lines = [
        "pub trait Upgrade<T> {",
        "    fn upgrade(self) -> T;",
        "}",
        "",
        "pub trait Downgrade<T> {",
        "    fn downgrade(self) -> Result<T, LossReport>;",
        "}",
        "",
        "#[derive(Debug, Clone, PartialEq)]",
        "pub struct LossReport {",
        "    pub dropped_fields: Vec<&'static str>,",
        "}",
        "",
        f"impl Upgrade<{v2}> for {v1} {{",
        f"    fn upgrade(self) -> {v2} {{",
        f"        {v2} {{",
    ]
    for name, nt in new_t.items():
        if name in old_t and old_t[name] == nt:
            lines.append(f"            {name}: self.{name},")
        elif name in old_t:
            lines.append(f'            {name}: todo!("retype {name}: {old_t[name]} -> {nt}"),')
        elif name in new_optional:
            lines.append(f"            {name}: None,")
        else:
            lines.append(f'            {name}: todo!("added required field {name}"),')
    lines += ["        }", "    }", "}", ""]

    dropped = [n for n in new_t if n not in old_t]
    lines.append(f"impl Downgrade<{v1}> for {v2} {{")
    lines.append(f"    fn downgrade(self) -> Result<{v1}, LossReport> {{")
    if dropped:
        joined = ", ".join(f'"{d}"' for d in dropped)
        lines.append(f"        let _loss = LossReport {{ dropped_fields: vec![{joined}] }};")
    lines.append(f"        Ok({v1} {{")
    for name, ot in old_t.items():
        if name in new_t and new_t[name] == ot:
            lines.append(f"            {name}: self.{name},")
        elif name in new_t:
            lines.append(f'            {name}: todo!("retype {name}"),')
        else:
            lines.append(f'            {name}: todo!("field {name} absent in V2"),')
    lines += ["        })", "    }", "}"]
    return lines


def _ts_interface(name: str, rec: IRRecord) -> list[str]:
    lines = [f"export interface {name} {{"]
    for f in rec.fields:
        if f.range is not None:
            lines.append(f"  /** {range_comment_text(f.range.min, f.range.max)} */")
        opt = "?" if f.type.kind == "option" else ""
        lines.append(f"  {f.name}{opt}: {_ts_type(f.type)};")
    lines.append("}")
    return lines


def render_typescript(old: IR, new: IR, type_name: str) -> str:
    old_rec = _find_record(old, type_name)
    new_rec = _find_record(new, type_name)
    verdict = classify(diff(old, new))
    rec_lookup = _record_lookup(new, old)
    var_lookup = _variant_lookup(new, old)
    refs = _referenced_types([old_rec, new_rec], rec_lookup, type_name)
    lines = [
        "// AUTO-GENERATED by aegis-interface (RFC 0005 §5.2). DO NOT EDIT.",
        "",
    ]
    for name in sorted(n for n in refs if n in var_lookup):
        v = var_lookup[name]
        union = " | ".join(f'"{c}"' for c in v.cases)
        lines.append(f"export type {v.name} = {union};")
        lines.append("")
    for name in sorted(n for n in refs if n in rec_lookup):
        lines += _ts_interface(name, rec_lookup[name])
        lines.append("")
    lines += _ts_interface(f"{type_name}V1", old_rec)
    lines.append("")
    lines += _ts_interface(f"{type_name}V2", new_rec)
    lines.append("")
    lines.append("// Structural compatibility assertion derived from the evolution verdict.")
    lines.append("// Compiles only while the asserted assignability holds.")
    lines.append("type AssertAssignable<Sup, Sub extends Sup> = true;")
    lines.append("")
    lines.append(f"// evolution verdict: {verdict}")
    if verdict in (VERDICT_FULL, VERDICT_BACKWARD):
        # backward compatible: V2 has at least V1's required surface -> V2 assignable to V1
        lines.append(
            f"export type Verify_{type_name}_Backward = "
            f"AssertAssignable<{type_name}V1, {type_name}V2>;"
        )
    if verdict in (VERDICT_FULL, VERDICT_FORWARD):
        lines.append(
            f"export type Verify_{type_name}_Forward = "
            f"AssertAssignable<{type_name}V2, {type_name}V1>;"
        )
    if verdict == VERDICT_BREAKING:
        lines.append("// BREAKING: no safe structural assignment exists in either direction.")
    return "\n".join(lines).rstrip("\n") + "\n"
