import WeilMixedAlgebraV2
import WeilThreeBlockTranslatedPacketsV22
import WeilMellinInversionV1
import WeilAutocorrelationPoleAggregationV1
import Mathlib.Tactic

/-!
AEGIS Ω — finite-dilation moment filter V10.

This is the constructive filter used in the restricted-Weil converse:

  A g(x) = g(x) - 3 g(2x) + 2 g(4x).

The implementation deliberately reuses the already-formalized translated-packet
and packet linear-algebra closures.  The new content is:

* an exact packet-level dilation g(x) ↦ g(2x);
* Mellin scaling under that dilation;
* the polynomial Mellin multiplier
    1 - 3·2^(-s) + 2·(2^(-s))^2;
* automatic annihilation of the repository's s=0 and s=1 Mellin moments.

No RH or positivity assumption is used.

AUTHORITY_EFFECT = NONE.
-/

open Set Complex MeasureTheory
open scoped BigOperators

set_option autoImplicit false
noncomputable section

namespace AEGIS.WeilFiniteDilationFilterV10

open AEGIS.WeilMixedAlgebraV2
open AEGIS.WeilThreeBlockTranslatedPacketsV22

/-- Exact packet-level dilation g(x) ↦ g(2x), built from the existing
log-translation packet and an amplitude cancellation. -/
def dilateTwoPacketV10 (g : WeilCompactSmoothGV1) : WeilCompactSmoothGV1 :=
  scalePacket
    ((Real.exp (-(Real.log 2) / 2) : ℝ) : ℂ)
    (translatePacket g (-(Real.log 2)))

@[simp] theorem dilateTwoPacket_apply_v10
    (g : WeilCompactSmoothGV1) (x : ℝ) :
    (dilateTwoPacketV10 g).1 x = g.1 (2 * x) := by
  change
    ((Real.exp (-(Real.log 2) / 2) : ℝ) : ℂ) *
      (((Real.exp (-(-(Real.log 2)) / 2) : ℝ) : ℂ) *
        g.1 (Real.exp (-(-(Real.log 2))) * x)) =
      g.1 (2 * x)
  have h2 : (0 : ℝ) < 2 := by norm_num
  have hscalar :
      ((Real.exp (-(Real.log 2) / 2) : ℝ) : ℂ) *
        ((Real.exp (Real.log 2 / 2) : ℝ) : ℂ) = 1 := by
    rw [← Complex.ofReal_mul, ← Real.exp_add]
    have hzero : -(Real.log 2) / 2 + Real.log 2 / 2 = 0 := by ring
    rw [hzero, Real.exp_zero]
    simp
  rw [show -(-(Real.log 2)) / 2 = Real.log 2 / 2 by ring,
    show -(-(Real.log 2)) = Real.log 2 by ring,
    Real.exp_log h2]
  rw [← mul_assoc, hscalar, one_mul]

/-- Dilation by four is two exact dilations by two. -/
def dilateFourPacketV10 (g : WeilCompactSmoothGV1) : WeilCompactSmoothGV1 :=
  dilateTwoPacketV10 (dilateTwoPacketV10 g)

@[simp] theorem dilateFourPacket_apply_v10
    (g : WeilCompactSmoothGV1) (x : ℝ) :
    (dilateFourPacketV10 g).1 x = g.1 (4 * x) := by
  simp [dilateFourPacketV10, dilateTwoPacket_apply_v10]
  congr 1
  ring

/-- The actual finite-dilation filter packet. -/
def finiteDilationFilterV10 (g : WeilCompactSmoothGV1) :
    WeilCompactSmoothGV1 :=
  addPacket g
    (addPacket
      (scalePacket (-3 : ℂ) (dilateTwoPacketV10 g))
      (scalePacket (2 : ℂ) (dilateFourPacketV10 g)))

@[simp] theorem finiteDilationFilter_apply_v10
    (g : WeilCompactSmoothGV1) (x : ℝ) :
    (finiteDilationFilterV10 g).1 x =
      g.1 x - 3 * g.1 (2 * x) + 2 * g.1 (4 * x) := by
  simp [finiteDilationFilterV10, addPacket, scalePacket,
    dilateTwoPacket_apply_v10, dilateFourPacket_apply_v10]
  ring

/-- Mellin scaling for the exact packet-level doubling. -/
theorem mellin_dilateTwoPacket_v10
    (g : WeilCompactSmoothGV1) (s : ℂ) :
    mellin (dilateTwoPacketV10 g).1 s =
      (2 : ℂ) ^ (-s) * mellin g.1 s := by
  have hfun :
      (dilateTwoPacketV10 g).1 = fun x : ℝ => g.1 (2 * x) := by
    funext x
    exact dilateTwoPacket_apply_v10 g x
  rw [hfun]
  simpa [smul_eq_mul] using
    (mellin_comp_mul_left g.1 s (a := (2 : ℝ)) (by norm_num))

/-- Mellin scaling for the doubled dilation. -/
theorem mellin_dilateFourPacket_v10
    (g : WeilCompactSmoothGV1) (s : ℂ) :
    mellin (dilateFourPacketV10 g).1 s =
      ((2 : ℂ) ^ (-s)) ^ 2 * mellin g.1 s := by
  unfold dilateFourPacketV10
  rw [mellin_dilateTwoPacket_v10, mellin_dilateTwoPacket_v10]
  ring

/-- Packet scalar multiplication commutes with Mellin transform. -/
theorem mellin_scalePacket_v10
    (z : ℂ) (g : WeilCompactSmoothGV1) (s : ℂ) :
    mellin (scalePacket z g).1 s = z * mellin g.1 s := by
  simpa [scalePacket, smul_eq_mul] using
    (mellin_const_smul g.1 s z)

/-- Polynomial multiplier generated by the finite dilation filter. -/
def finiteDilationMultiplierV10 (s : ℂ) : ℂ :=
  1 - 3 * (2 : ℂ) ^ (-s) + 2 * (((2 : ℂ) ^ (-s)) ^ 2)

/-- Exact Mellin factorization of the finite-dilation filter. -/
theorem mellin_finiteDilationFilter_v10
    (g : WeilCompactSmoothGV1) (s : ℂ) :
    mellin (finiteDilationFilterV10 g).1 s =
      finiteDilationMultiplierV10 s * mellin g.1 s := by
  let d2 := dilateTwoPacketV10 g
  let d4 := dilateFourPacketV10 g
  let a := scalePacket (-3 : ℂ) d2
  let b := scalePacket (2 : ℂ) d4
  have hg := weil_compact_smooth_mellin_convergent_all_v1 g s
  have ha := weil_compact_smooth_mellin_convergent_all_v1 a s
  have hb := weil_compact_smooth_mellin_convergent_all_v1 b s
  have hab := hasMellin_add ha hb
  have htotal := hasMellin_add hg hab.1
  have hsum :
      mellin (finiteDilationFilterV10 g).1 s =
        mellin g.1 s + (mellin a.1 s + mellin b.1 s) := by
    simpa [finiteDilationFilterV10, a, b, d2, d4, addPacket]
      using htotal.2
  rw [hsum]
  rw [mellin_scalePacket_v10, mellin_scalePacket_v10]
  dsimp [a, b, d2, d4]
  rw [mellin_dilateTwoPacket_v10, mellin_dilateFourPacket_v10]
  unfold finiteDilationMultiplierV10
  ring

/-- The filter multiplier vanishes at s=0. -/
theorem finiteDilationMultiplier_zero_v10 :
    finiteDilationMultiplierV10 0 = 0 := by
  simp [finiteDilationMultiplierV10]

/-- The filter multiplier vanishes at s=1. -/
theorem finiteDilationMultiplier_one_v10 :
    finiteDilationMultiplierV10 1 = 0 := by
  rw [finiteDilationMultiplierV10]
  norm_num [Complex.cpow_neg_one]

theorem mellin_finiteDilationFilter_zero_v10
    (g : WeilCompactSmoothGV1) :
    mellin (finiteDilationFilterV10 g).1 0 = 0 := by
  rw [mellin_finiteDilationFilter_v10,
    finiteDilationMultiplier_zero_v10, zero_mul]

theorem mellin_finiteDilationFilter_one_v10
    (g : WeilCompactSmoothGV1) :
    mellin (finiteDilationFilterV10 g).1 1 = 0 := by
  rw [mellin_finiteDilationFilter_v10,
    finiteDilationMultiplier_one_v10, zero_mul]

/-- The finite-dilation filter automatically discharges the exact two
repository moment conditions. -/
theorem finiteDilationFilter_moments_v10
    (g : WeilCompactSmoothGV1) :
    WeilMomentConditionsV1 (finiteDilationFilterV10 g) := by
  constructor
  · rw [← weil_mellin_zero_eq_moment0_v1 (finiteDilationFilterV10 g)]
    exact mellin_finiteDilationFilter_zero_v10 g
  · rw [← weil_mellin_one_eq_moment1_v1 (finiteDilationFilterV10 g)]
    exact mellin_finiteDilationFilter_one_v10 g

end AEGIS.WeilFiniteDilationFilterV10

#print axioms AEGIS.WeilFiniteDilationFilterV10.mellin_dilateTwoPacket_v10
#print axioms AEGIS.WeilFiniteDilationFilterV10.mellin_finiteDilationFilter_v10
#print axioms AEGIS.WeilFiniteDilationFilterV10.finiteDilationFilter_moments_v10
