import Mathlib.Analysis.SpecialFunctions.Integrals.Basic
import Mathlib.Tactic

/-!
AEGIS Ω — finite single-frequency source calculus v1.

This file proves the finite algebra/analysis identity underlying the
single-frequency step of the Guinand--Weil source calculus.

For

  ψ_{α,ω}(x) = (α / π) sin(2 π ω x),

the divided-difference entry of the source is exactly α times the real
termwise Volterra/chord contribution. Summing over a finite frequency band
therefore identifies the finite quadratic contraction with α times the
expanded real chord kernel.

`WeilChordKernelV1` is deliberately the finite real termwise expansion. This
file does NOT yet prove its equality with the real part of the single compact
integral `2 ∫ T(t) T(ω-t) dt`; that finite-sum/integral interchange and the
even-symmetry cancellation can be added as a separate strengthening without
changing any theorem proved here.

No zeta-zero statement, PSD claim, global Weil positivity, or RH claim is made.
-/

open scoped BigOperators
open intervalIntegral

set_option autoImplicit false

noncomputable section

/-- One sinusoidal source atom in the finite Guinand--Weil source calculus. -/
def WeilSingleFrequencySourceV1 (α ω x : ℝ) : ℝ :=
  α / Real.pi * Real.sin (2 * Real.pi * ω * x)

/-- The divided-difference matrix entry generated by one sinusoidal source.
The diagonal is the derivative value. -/
def WeilSingleFrequencyEntryV1 (α ω : ℝ) (m n : ℤ) : ℝ :=
  if m = n then
    2 * α * ω * Real.cos (2 * Real.pi * ω * (m : ℝ))
  else
    (WeilSingleFrequencySourceV1 α ω (m : ℝ) -
      WeilSingleFrequencySourceV1 α ω (n : ℝ)) /
      ((m : ℝ) - (n : ℝ))

/-- The finite complex trigonometric polynomial used by the paper-level
Volterra construction. It is exposed here to freeze the intended carrier;
the v1 theorem below works with the exactly equivalent termwise real
expansion and therefore does not need a sum/integral interchange. -/
def WeilTrigPolynomialV1 (N : ℕ) (u : ℤ → ℝ) (t : ℝ) : ℂ :=
  ∑ m ∈ Finset.Icc (-(N : ℤ)) (N : ℤ),
    (u m : ℂ) * Complex.exp
      ((2 * Real.pi * (m : ℝ) * t : ℝ) * Complex.I)

/-- Real contribution of the ordered pair `(m,n)` to the expanded chord
kernel. -/
def WeilChordPairV1 (ω : ℝ) (m n : ℤ) : ℝ :=
  2 * ∫ t in (0 : ℝ)..ω,
    Real.cos
      (2 * Real.pi *
        (((m : ℝ) - (n : ℝ)) * t + (n : ℝ) * ω))

/-- Finite real termwise Volterra/chord kernel on the symmetric band. -/
def WeilChordKernelV1 (N : ℕ) (u : ℤ → ℝ) (ω : ℝ) : ℝ :=
  ∑ m ∈ Finset.Icc (-(N : ℤ)) (N : ℤ),
    ∑ n ∈ Finset.Icc (-(N : ℤ)) (N : ℤ),
      u m * u n * WeilChordPairV1 ω m n

/-- Finite quadratic contraction of the one-frequency divided-difference
matrix. -/
def WeilSingleFrequencyQuadraticV1
    (N : ℕ) (u : ℤ → ℝ) (α ω : ℝ) : ℝ :=
  ∑ m ∈ Finset.Icc (-(N : ℤ)) (N : ℤ),
    ∑ n ∈ Finset.Icc (-(N : ℤ)) (N : ℤ),
      u m * u n * WeilSingleFrequencyEntryV1 α ω m n

private theorem integral_cos_affine_v1
    (A B a b : ℝ) (hA : A ≠ 0) :
    (∫ t in a..b, Real.cos (A * t + B)) =
      (Real.sin (A * b + B) - Real.sin (A * a + B)) / A := by
  rw [sub_div]
  apply integral_eq_sub_of_hasDerivAt
  swap
  · exact (Real.continuous_cos.comp
      ((continuous_const.mul continuous_id).add continuous_const)).intervalIntegrable a b
  intro x _
  have hlin : HasDerivAt (fun y : ℝ => A * y + B) A x := by
    simpa using ((hasDerivAt_id x).const_mul A).add_const B
  have hsin := (Real.hasDerivAt_sin (A * x + B)).comp x hlin
  simpa [hA] using hsin.div_const A

/-- Off the diagonal, the real Volterra pair integral is exactly the source
divided difference. -/
theorem weil_single_frequency_source_offdiag_v1
    (α ω : ℝ) (m n : ℤ) (hmn : m ≠ n) :
    WeilSingleFrequencyEntryV1 α ω m n =
      α * WeilChordPairV1 ω m n := by
  have hmnR : (m : ℝ) ≠ (n : ℝ) := by exact_mod_cast hmn
  have hd : (m : ℝ) - (n : ℝ) ≠ 0 := sub_ne_zero.mpr hmnR
  have hA : 2 * Real.pi * ((m : ℝ) - (n : ℝ)) ≠ 0 := by
    exact mul_ne_zero (mul_ne_zero (by norm_num) Real.pi_ne_zero) hd
  have hfun :
      (fun t : ℝ =>
        Real.cos
          (2 * Real.pi * (((m : ℝ) - (n : ℝ)) * t + (n : ℝ) * ω))) =
      (fun t : ℝ =>
        Real.cos
          ((2 * Real.pi * ((m : ℝ) - (n : ℝ))) * t +
            2 * Real.pi * (n : ℝ) * ω)) := by
    funext t
    congr 1
    ring
  have hmarg :
      (2 * Real.pi * ((m : ℝ) - (n : ℝ))) * ω +
          2 * Real.pi * (n : ℝ) * ω =
        2 * Real.pi * ω * (m : ℝ) := by
    ring
  have hnarg :
      (2 * Real.pi * ((m : ℝ) - (n : ℝ))) * 0 +
          2 * Real.pi * (n : ℝ) * ω =
        2 * Real.pi * ω * (n : ℝ) := by
    ring
  rw [WeilSingleFrequencyEntryV1, if_neg hmn]
  unfold WeilChordPairV1
  rw [hfun]
  rw [integral_cos_affine_v1
    (2 * Real.pi * ((m : ℝ) - (n : ℝ)))
    (2 * Real.pi * (n : ℝ) * ω) 0 ω hA]
  rw [hmarg, hnarg]
  unfold WeilSingleFrequencySourceV1
  field_simp [Real.pi_ne_zero, hd]
  ring

/-- On the diagonal, the same pair integral is the derivative entry. -/
theorem weil_single_frequency_source_diagonal_v1
    (α ω : ℝ) (m : ℤ) :
    WeilSingleFrequencyEntryV1 α ω m m =
      α * WeilChordPairV1 ω m m := by
  simp [WeilSingleFrequencyEntryV1, WeilChordPairV1]

private theorem weil_single_frequency_entry_eq_chord_pair_v1
    (α ω : ℝ) (m n : ℤ) :
    WeilSingleFrequencyEntryV1 α ω m n =
      α * WeilChordPairV1 ω m n := by
  by_cases hmn : m = n
  · subst n
    exact weil_single_frequency_source_diagonal_v1 α ω m
  · exact weil_single_frequency_source_offdiag_v1 α ω m n hmn

/-- Finite source calculus, in its exact real termwise Volterra form:
the quadratic contraction of a one-frequency divided-difference matrix equals
`α` times the expanded chord kernel. -/
theorem weil_single_frequency_source_calculus_v1
    (N : ℕ) (u : ℤ → ℝ) (α ω : ℝ) :
    WeilSingleFrequencyQuadraticV1 N u α ω =
      α * WeilChordKernelV1 N u ω := by
  simp only [WeilSingleFrequencyQuadraticV1, WeilChordKernelV1]
  simp_rw [weil_single_frequency_entry_eq_chord_pair_v1]
  simp [Finset.mul_sum, mul_left_comm, mul_comm]

#print axioms weil_single_frequency_source_offdiag_v1
#print axioms weil_single_frequency_source_diagonal_v1
#print axioms weil_single_frequency_source_calculus_v1
