import { createHash, randomBytes } from 'node:crypto';
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';

export const PLANS = {
  explorer: { name: 'Explorer', requests: 100, tokens: 100_000, spendCents: 0, priceCents: 0, models: ['aegis-demo'], retentionDays: 7 },
  operator: { name: 'Operator', requests: 10_000, tokens: 10_000_000, spendCents: 4_900, priceCents: 4_900, models: ['aegis-demo', 'gemini'], retentionDays: 30 },
  sovereign: { name: 'Sovereign', requests: 100_000, tokens: 100_000_000, spendCents: 49_900, priceCents: 49_900, models: ['aegis-demo', 'gemini', 'claude'], retentionDays: 90 },
};

const sha256 = (value) => createHash('sha256').update(value).digest('hex');
const periodStart = (date = new Date()) => new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), 1)).toISOString();
const periodEnd = (date = new Date()) => new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth() + 1, 1)).toISOString();

export class ProductService {
  constructor({ file = process.env.PRODUCT_STATE_FILE || '.data/product-state.json', now = () => new Date() } = {}) {
    this.file = file; this.now = now; this.state = { accounts: {}, webhookEvents: {} }; this.ready = this.load();
  }
  async load() { try { this.state = JSON.parse(await readFile(this.file, 'utf8')); } catch (error) { if (error.code !== 'ENOENT') throw error; } }
  async save() { await mkdir(dirname(this.file), { recursive: true }); const tmp = `${this.file}.tmp`; await writeFile(tmp, JSON.stringify(this.state, null, 2)); await rename(tmp, this.file); }
  async account(id = 'default') { await this.ready; if (!this.state.accounts[id]) this.state.accounts[id] = { id, plan: 'explorer', apiKeys: [], usage: [], notifications: [80, 100], invoices: [], analytics: [], createdAt: this.now().toISOString() }; return this.state.accounts[id]; }
  async createApiKey(accountId, name = 'Default key') { const account = await this.account(accountId); const secret = `aegis_${randomBytes(24).toString('base64url')}`; const key = { id: `key_${randomBytes(8).toString('hex')}`, name, prefix: secret.slice(0, 14), hash: sha256(secret), createdAt: this.now().toISOString(), lastUsedAt: null, revokedAt: null }; account.apiKeys.push(key); await this.save(); return { secret, key: this.safeKey(key) }; }
  safeKey(key) { const { hash, ...safe } = key; return safe; }
  async authenticate(secret) { await this.ready; const hash = sha256(secret || ''); for (const account of Object.values(this.state.accounts)) { const key = account.apiKeys.find((candidate) => candidate.hash === hash && !candidate.revokedAt); if (key) { key.lastUsedAt = this.now().toISOString(); await this.save(); return { account, key }; } } return null; }
  quota(account) { const plan = PLANS[account.plan]; const start = periodStart(this.now()); const entries = account.usage.filter((entry) => entry.at >= start); const used = entries.reduce((total, entry) => ({ requests: total.requests + entry.requests, tokens: total.tokens + entry.tokens, spendCents: total.spendCents + entry.spendCents }), { requests: 0, tokens: 0, spendCents: 0 }); const limits = { requests: plan.requests, tokens: plan.tokens, spendCents: plan.spendCents }; return { period: { start, end: periodEnd(this.now()) }, plan: account.plan, limits, used, remaining: Object.fromEntries(Object.entries(limits).map(([k, v]) => [k, Math.max(0, v - used[k])])), utilization: Object.fromEntries(Object.entries(limits).map(([k, v]) => [k, v === 0 ? 0 : used[k] / v])) }; }
  headers(quota) { return { 'X-Quota-Plan': quota.plan, 'X-Quota-Requests-Limit': String(quota.limits.requests), 'X-Quota-Requests-Remaining': String(quota.remaining.requests), 'X-Quota-Tokens-Limit': String(quota.limits.tokens), 'X-Quota-Tokens-Remaining': String(quota.remaining.tokens), 'X-Quota-Spend-Limit-Cents': String(quota.limits.spendCents), 'X-Quota-Spend-Remaining-Cents': String(quota.remaining.spendCents), 'X-Quota-Reset': quota.period.end }; }
  async recordUsage(account, usage, { meteringFailed = false } = {}) { const quota = this.quota(account); const over = Object.keys(usage).find((key) => usage[key] > quota.remaining[key]); const graceUsed = account.usage.filter((entry) => entry.at >= quota.period.start && entry.meteringStatus === 'grace').reduce((total, entry) => total + entry.requests, 0); if (meteringFailed && graceUsed + usage.requests > 5) return { allowed: false, quota, dimension: 'metering_grace' }; if (over && !meteringFailed) return { allowed: false, quota, dimension: over }; const entry = { at: this.now().toISOString(), requests: usage.requests || 0, tokens: usage.tokens || 0, spendCents: usage.spendCents || 0, meteringStatus: meteringFailed ? 'grace' : 'recorded' }; account.usage.push(entry); const crossed = account.notifications.filter((threshold) => quota.utilization.requests < threshold / 100 && (quota.used.requests + entry.requests) / quota.limits.requests >= threshold / 100); if (crossed.length) account.analytics.push({ event: 'quota_warning', at: entry.at, properties: { thresholds: crossed } }); await this.save(); return { allowed: true, quota: this.quota(account), grace: meteringFailed }; }
  async overview(account) { const quota = this.quota(account); const elapsed = Math.max(1, this.now() - new Date(quota.period.start)); const period = Math.max(elapsed, new Date(quota.period.end) - new Date(quota.period.start)); const project = (value) => Math.round(value / elapsed * period); return { plan: { id: account.plan, ...PLANS[account.plan] }, quota, projectedPeriodEnd: { requests: project(quota.used.requests), tokens: project(quota.used.tokens), spendCents: project(quota.used.spendCents) }, usageHistory: account.usage, apiKeys: account.apiKeys.map((key) => this.safeKey(key)), invoices: account.invoices, notificationThresholds: account.notifications, gracePolicy: { enabled: true, scope: 'transient metering failures only', maxRequests: 5 } }; }
  async revokeKey(account, id) { const key = account.apiKeys.find((item) => item.id === id); if (!key) return false; key.revokedAt = this.now().toISOString(); await this.save(); return true; }
  async configureNotifications(account, thresholds) { if (!Array.isArray(thresholds) || thresholds.some((x) => !Number.isInteger(x) || x < 1 || x > 100)) throw new Error('thresholds must be integer percentages from 1 through 100'); account.notifications = [...new Set(thresholds)].sort((a, b) => a - b); await this.save(); return account.notifications; }
  async checkout(account, plan) { if (!PLANS[plan] || plan === 'explorer') throw new Error('plan is not available for checkout'); const id = `checkout_${randomBytes(8).toString('hex')}`; account.analytics.push({ event: 'checkout_start', at: this.now().toISOString(), properties: { plan, checkoutId: id } }); await this.save(); return { id, plan, status: 'pending_payment', checkoutUrl: `${process.env.BILLING_CHECKOUT_URL || 'https://billing.example.invalid/checkout'}?checkout_id=${id}` }; }
  async applyWebhook(event) { await this.ready; if (!event?.id || !event?.type || !event?.data?.accountId) throw new Error('invalid billing event'); if (this.state.webhookEvents[event.id]) return { duplicate: true }; if (event.type !== 'entitlement.granted') throw new Error('unsupported billing event'); const account = await this.account(event.data.accountId); if (!PLANS[event.data.plan]) throw new Error('unknown plan'); account.plan = event.data.plan; account.invoices.unshift({ id: event.data.invoiceId || event.id, amountCents: PLANS[account.plan].priceCents, status: 'paid', issuedAt: this.now().toISOString(), plan: account.plan }); account.analytics.push({ event: 'conversion', at: this.now().toISOString(), properties: { plan: account.plan } }); this.state.webhookEvents[event.id] = { appliedAt: this.now().toISOString() }; await this.save(); return { duplicate: false, plan: account.plan }; }
  async track(account, event, properties = {}) { const allowed = new Set(['signup', 'api_key_created', 'first_successful_request', 'quota_warning', 'checkout_start', 'conversion', 'churn', 'reactivation']); if (!allowed.has(event)) throw new Error('unsupported funnel event'); const { prompt, promptContent, messages, ...safe } = properties; account.analytics.push({ event, at: this.now().toISOString(), properties: safe }); await this.save(); }
}
