import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
const ts=createRequire(import.meta.url)('typescript');
async function load(path){const s=readFileSync(new URL('../../src/'+path,import.meta.url),'utf8');const j=ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;return import('data:text/javascript;base64,'+Buffer.from(j).toString('base64'));}
const managed=await load('sovereignty/provider-adapters/openai-managed-agents-api.ts');
const company=await load('sovereignty/autonomous-company-loop.ts');
function binding(states=[{id:'s1',status:'idle'}]){let i=0;const creates=[];return {creates,api:{create:async x=>(creates.push(x),states[0]),retrieve:async()=>states[Math.min(++i,states.length-1)],finalOutput:async()=> 'ok'}};}
function sha(d,v){return Promise.resolve(createHash('sha256').update(d+'\n'+JSON.stringify(v)).digest('hex'));}
function t(id,action='ANALYZE'){return {task_id:id,department:'engineering',objective:'do '+id,action_class:action};}

test('managed construction is inert and uses bounded multi-agent session',async()=>{const f=binding();const r=managed.createOpenAIManagedAgentsApiRunnerV1({binding:f.api,model:'gpt-6-astra',tools:[{id:'web',effect:'NONE',api_tool:{type:'web_search'}}]});assert.equal(f.creates.length,0);const out=await r.run({instructions:'evidence',task:'research'});assert.equal(out.authority_effect,'NONE');assert.deepEqual(f.creates[0].agent.multi_agent,{enabled:true,max_concurrent_subagents:3});assert.deepEqual(f.creates[0].agent.tools,[{type:'web_search'}]);});
test('managed required action and external mutation tool fail closed',async()=>{const f=binding([{id:'s1',status:'requires_action',required_actions:[{type:'function_call',name:'send_email'}]}]);const r=managed.createOpenAIManagedAgentsApiRunnerV1({binding:f.api,model:'gpt-6-astra'});await assert.rejects(r.run({instructions:'x',task:'y'}),/REQUIRES_ACTION:send_email/);assert.throws(()=>managed.createOpenAIManagedAgentsApiRunnerV1({binding:f.api,model:'gpt-6-astra',tools:[{id:'mail',effect:'EXTERNAL_MUTATION',api_tool:{type:'mcp'}}]}),/NOT_ADMITTED/);});
test('managed polling enforces session identity',async()=>{const f=binding([{id:'s1',status:'in_progress'},{id:'s2',status:'idle'}]);const r=managed.createOpenAIManagedAgentsApiRunnerV1({binding:f.api,model:'gpt-6-astra'});await assert.rejects(r.run({instructions:'x',task:'y'}),/ID_DRIFT/);});
test('safe work runs autonomously but consequential work waits',async()=>{const executed=[];const auth=[];const loop=company.createAutonomousCompanyLoopV1({planner:{plan:async()=>({tasks:[t('r','RESEARCH_READ'),t('d','DEPLOY')]})},executor:{execute:async x=>(executed.push(x.task_id),{output:'ok',evidence:{}})},verifier:{verify:async()=>({verdict:'PASS',reason:'ok'})},authorize:async x=>(auth.push(x.task_id),false),hash:sha});const receipt=await loop.run('operate');assert.deepEqual(executed,['r']);assert.deepEqual(auth,['d']);assert.equal(receipt.completed,1);assert.equal(receipt.awaiting_operator,1);});
test('verifier failure cannot become verified work',async()=>{const loop=company.createAutonomousCompanyLoopV1({planner:{plan:async()=>({tasks:[t('x')]})},executor:{execute:async()=>({output:'bad',evidence:{}})},verifier:{verify:async()=>({verdict:'FAIL',reason:'failed'})},hash:sha});const r=await loop.run('verify');assert.equal(r.completed,0);assert.equal(r.rejected,1);});
test('duplicate task IDs and invalid hashes fail closed',async()=>{const base={planner:{plan:async()=>({tasks:[t('x'),t('x')]})},executor:{execute:async()=>({output:'x',evidence:{}})},verifier:{verify:async()=>({verdict:'PASS',reason:'ok'})},hash:sha};await assert.rejects(company.createAutonomousCompanyLoopV1(base).run('x'),/DUPLICATE/);await assert.rejects(company.createAutonomousCompanyLoopV1({...base,planner:{plan:async()=>({tasks:[t('a')]})},hash:async()=> 'bad'}).run('x'),/SHA-256/);});
