
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/aegisomegav1/locations/us-central1/spaces/default-space/applicationTemplates/app-template-1

module "regional-lb-frontend" {
  source        = "github.com/GoogleCloudPlatform/terraform-google-regional-lb-http//modules/frontend?ref=v0.12.2"
  project_id    = var.regional-lb-frontend_project_id
  region        = var.regional-lb-frontend_region
  name          = var.regional-lb-frontend_name
  network       = var.regional-lb-frontend_network
  url_map_input = module.regional-lb-backend.backend_service_info
}
module "memorystore" {
  source                  = "github.com/terraform-google-modules/terraform-google-memorystore?ref=v15.2.2"
  project_id              = var.memorystore_project_id
  region                  = var.memorystore_region
  name                    = var.memorystore_name
  tier                    = "BASIC"
  memory_size_gb          = 16
  redis_version           = "REDIS_6_X"
  connect_mode            = "DIRECT_PEERING"
  read_replicas_mode      = "READ_REPLICAS_ENABLED"
  replica_count           = 1
  location_id             = "us-central1-a"
  auth_enabled            = true
  transit_encryption_mode = "DISABLED"
  persistence_config = {
    persistence_mode    = "RDB"
    rdb_snapshot_period = "ONE_HOUR"
  }
}
module "frontend-service-cloud-run" {
  source       = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.31.0"
  project_id   = var.frontend-service-cloud-run_project_id
  location     = var.frontend-service-cloud-run_location
  service_name = var.frontend-service-cloud-run_service_name
  containers = [
    {
      container_image = "us-central1-docker.pkg.dev/aegisomegav1/aegis-registry/hub:latest"
      container_name  = "service-container"
      env_vars = {
        backend_service_cloud_run_SERVICE_ENDPOINT = module.backend-service-cloud-run.service_uri
      }
      ports = {
        container_port = 80
        name           = "http1"
      }
      resources = {
        cpu_idle          = true
        startup_cpu_boost = false
      }
    },
  ]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = [
    "roles/run.invoker",
  ]
  ingress = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "PRIVATE_RANGES_ONLY"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = false
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "database-postgresql" {
  source              = "github.com/terraform-google-modules/terraform-google-sql-db//modules/postgresql?ref=v26.2.2"
  project_id          = var.database-postgresql_project_id
  region              = var.database-postgresql_region
  name                = var.database-postgresql_name
  edition             = "ENTERPRISE_PLUS"
  database_version    = var.database-postgresql_database_version
  availability_type   = "REGIONAL"
  deletion_protection = false
  database_flags = [
    {
      name  = "cloudsql.iam_authentication"
      value = "on"
    },
  ]
  database_deletion_policy    = "ABANDON"
  user_deletion_policy        = "ABANDON"
  data_cache_enabled          = true
  tier                        = "db-perf-optimized-N-8"
  deletion_protection_enabled = false
  disk_autoresize             = true
  backup_configuration = {
    enabled                        = true
    point_in_time_recovery_enabled = true
  }
  iam_users = [
    {
      email = module.backend-service-cloud-run.service_account_id.email
      id    = module.backend-service-cloud-run.service_account_id.id
      type  = "CLOUD_IAM_SERVICE_ACCOUNT"
    },
  ]
}
module "backend-service-cloud-run" {
  source       = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.31.0"
  project_id   = var.backend-service-cloud-run_project_id
  location     = var.backend-service-cloud-run_location
  service_name = var.backend-service-cloud-run_service_name
  containers = [
    {
      container_image = "us-central1-docker.pkg.dev/aegisomegav1/aegis-registry/constitutional-proxy:latest"
      container_name  = "service-container"
      env_vars = merge(
        {
          "REDIS_URL"          = "redis://:${module.memorystore.auth_string}@${module.memorystore.host}:${module.memorystore.env_vars.REDIS_PORT}"
          "AEGIS_DEFAULT_MODEL" = "claude-opus-4-8"
        },
        { "database_postgresql_CLOUD_SQL_DATABASE_CONNECTION_NAME" = module.database-postgresql.instance_connection_name }
      )
      ports = {
        container_port = 8080
        name           = "http1"
      }
      resources = {
        cpu_idle          = true
        startup_cpu_boost = false
      }
      volume_mounts = [{
        mount_path = "/cloudsql"
        name       = "cloudsql"
      }]
    },
  ]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/cloudsql.instanceUser", "roles/cloudsql.client"], ["roles/redis.editor"])
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "PRIVATE_RANGES_ONLY"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "regional-lb-backend" {
  source     = "github.com/GoogleCloudPlatform/terraform-google-regional-lb-http//modules/backend?ref=v0.12.2"
  project_id = var.regional-lb-backend_project_id
  region     = var.regional-lb-backend_region
  name       = var.regional-lb-backend_name
  serverless_neg_backends = [
    {
      capacity_scaler = 1
      region          = module.frontend-service-cloud-run.location
      service_name    = module.frontend-service-cloud-run.service_name
      service_version = ""
      type            = "cloud-run"
    },
  ]
}
module "agent-registry-agent-1" {
  source     = "github.com/GoogleCloudPlatform/terraform-google-agent-registry//modules/agent-registry-agent?ref=v0.3.4"
  project_id = var.agent-registry-agent-1_project_id
  location   = var.agent-registry-agent-1_location
}
module "apphub" {
  source         = "github.com/GoogleCloudPlatform/terraform-google-apphub?ref=v0.4.0"
  project_id     = var.apphub_project_id
  location       = var.apphub_location
  service_uris   = concat(module.regional-lb-frontend.apphub_service_uri, [module.memorystore.apphub_service_uri], [module.frontend-service-cloud-run.apphub_service_uri], [module.database-postgresql.apphub_service_uri], [module.backend-service-cloud-run.apphub_service_uri])
  application_id = var.apphub_application_id
}
