
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/aegisomegav1/locations/us-central1/spaces/default-space/applicationTemplates/app-template-1

output "regional-lb-frontend_external_ip" {
  description = "The external IPv4 assigned to the fowarding rule."
  value       = module.regional-lb-frontend.external_ip
}
output "regional-lb-frontend_ip_address_http" {
  description = "The internal/external IP address assigned to the HTTP forwarding rule."
  value       = module.regional-lb-frontend.ip_address_http
}
output "regional-lb-frontend_ip_address_https" {
  description = "The internal/external IP address assigned to the HTTPS forwarding rule."
  value       = module.regional-lb-frontend.ip_address_https
}
output "memorystore_host" {
  description = "The IP address of the instance."
  value       = module.memorystore.host
}
output "memorystore_port" {
  description = "The port number of the exposed Redis endpoint."
  value       = module.memorystore.port
}
output "frontend-service-cloud-run_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.frontend-service-cloud-run.service_uri
}
output "backend-service-cloud-run_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.backend-service-cloud-run.service_uri
}
output "agent-registry-agent-1_agent_display_name" {
  description = "The display name of the Agent."
  value       = module.agent-registry-agent-1.agent_display_name
}
output "agent-registry-agent-1_agent_urn" {
  description = "The logical URN of the agent."
  value       = module.agent-registry-agent-1.agent_urn
}
