
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/aegisomegav1/locations/us-central1/spaces/default-space/applicationTemplates/app-template-1

variable "regional-lb-frontend_project_id" {
  description = "The project to deploy load balancer frontend resources.."
  type = string
}
variable "regional-lb-frontend_region" {
  description = "The region where the load balancer will be created"
  type = string
}
variable "regional-lb-frontend_name" {
  description = "Name for the forwarding rule and prefix for supporting resources"
  type = string
}
variable "regional-lb-frontend_network" {
  description = "VPC network for the forwarding rule. It should not be default. The VPC network should have only one REGIONAL_MANAGED_PROXY subnetwork in the same region as of this regional load balancer. Please go to the subnets tab of your VPC network and check if a REGIONAL_MANAGED_PROXY subnet exists under `Reserved proxy-only subnets for load balancing` section. If the REGIONAL_MANAGED_PROXY doesn't exists, set create_proxy_only_subnet parameter to provision it as part of this component deployment."
  type = string
}
variable "memorystore_project_id" {
  description = "The ID of the project in which the resource belongs to."
  type = string
}
variable "memorystore_region" {
  description = "The GCP region to use."
  type = string
}
variable "memorystore_name" {
  description = "The ID of the instance or a fully qualified identifier for the instance."
  type = string
}
variable "frontend-service-cloud-run_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "frontend-service-cloud-run_location" {
  description = "Cloud Run service deployment location"
  type = string
}
variable "frontend-service-cloud-run_service_name" {
  description = "The name of the Cloud Run service to create"
  type = string
}
variable "database-postgresql_project_id" {
  description = "The project ID to manage the Cloud SQL resources"
  type = string
}
variable "database-postgresql_region" {
  description = "The region of the Cloud SQL resources"
  default     = "us-central1"
  type = string
}
variable "database-postgresql_name" {
  description = "The name of the Cloud SQL instance"
  type = string
}
variable "database-postgresql_database_version" {
  description = "The database version to use. Can be 9_6, 14, 15, 16, 17."
  type = string
}
variable "backend-service-cloud-run_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "backend-service-cloud-run_location" {
  description = "Cloud Run service deployment location"
  type = string
}
variable "backend-service-cloud-run_service_name" {
  description = "The name of the Cloud Run service to create"
  type = string
}
variable "regional-lb-backend_project_id" {
  description = "The project to deploy load balancer backend resources."
  type = string
}
variable "regional-lb-backend_region" {
  description = "The region where the load balancer backend service will be created"
  type = string
}
variable "regional-lb-backend_name" {
  description = "Name for the load balancer backend service."
  type = string
}
variable "agent-registry-agent-1_project_id" {
  description = "The ID of the project in which the resource belongs."
  type = string
}
variable "agent-registry-agent-1_location" {
  description = "The location of the Agent Registry resource (e.g., us-central1)."
  type = string
}
variable "apphub_project_id" {
  description = "The project ID of the host project where AppHub application is created."
  type = string
}
variable "apphub_location" {
  description = "The location of AppHub application."
  type = string
}
variable "apphub_application_id" {
  description = "The AppHub application identifier"
  type = string
}
