import { useState } from 'react'
import { MONO } from './console/consoleTokens.js'

type Dashboard = { plan: { id: string; name: string; retentionDays: number; models: string[] }; quota: { period: { end: string }; limits: Record<string, number>; used: Record<string, number>; remaining: Record<string, number> }; projectedPeriodEnd: Record<string, number>; apiKeys: { id: string; name: string; prefix: string; createdAt: string; revokedAt?: string }[]; invoices: { id: string; amountCents: number; status: string }[]; notificationThresholds: number[]; gracePolicy: { scope: string } }
const api = (import.meta.env.VITE_PRODUCT_API_URL as string | undefined) ?? ''

export function DashboardPage() {
  const [key, setKey] = useState(localStorage.getItem('aegis_dashboard_key') ?? '')
  const [data, setData] = useState<Dashboard | null>(null)
  const [error, setError] = useState('')
  const load = async () => { try { const res = await fetch(`${api}/v1/dashboard`, { headers: { 'x-api-key': key } }); if (!res.ok) throw new Error('Enter an active API key to load your workspace.'); const next = await res.json() as Dashboard; localStorage.setItem('aegis_dashboard_key', key); setData(next); setError('') } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load dashboard') } }
  const createKey = async () => { const res = await fetch(`${api}/v1/api-keys`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-api-key': key }, body: JSON.stringify({ name: 'Dashboard key' }) }); const body = await res.json(); if (res.ok) { window.alert(`Copy this key now; it will not be shown again:\n${body.apiKey}`); void load() } }
  const upgrade = async (plan: string) => { const res = await fetch(`${api}/v1/billing/checkout`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-api-key': key }, body: JSON.stringify({ plan }) }); const body = await res.json(); if (res.ok) window.location.assign(body.checkoutUrl); else setError(body.error?.message ?? 'Checkout unavailable') }
  return <main className="min-h-screen px-6 py-12 text-white" style={{ background: '#06070C' }}><div className="max-w-5xl mx-auto">
    <a href="/" className="text-sm text-gray-400">← AEGIS-Ω</a><h1 className="text-3xl font-bold mt-8">Product dashboard</h1><p className="text-gray-400 mt-2">Usage, billing, API access, and plan controls.</p>
    {!data && <div className="mt-8 rounded-xl border border-gray-800 bg-gray-900 p-6"><label className="block text-sm mb-2">API key</label><div className="flex gap-3"><input value={key} onChange={e => setKey(e.target.value)} className="flex-1 rounded bg-black border border-gray-700 px-3 py-2 font-mono" placeholder="aegis_..."/><button onClick={() => void load()} className="rounded bg-indigo-500 px-4 py-2">Open dashboard</button></div>{error && <p className="text-red-300 text-sm mt-3">{error}</p>}</div>}
    {data && <><section className="grid md:grid-cols-3 gap-4 mt-8"><Card title="Current plan" value={data.plan.name} detail={`${data.plan.models.join(', ')} models · ${data.plan.retentionDays}-day retention`} /><Card title="Period ends" value={new Date(data.quota.period.end).toLocaleDateString()} detail="Entitlements change only after a confirmed billing webhook." /><Card title="Grace policy" value="Metering-safe" detail={data.gracePolicy.scope} /></section>
    <section className="mt-8"><h2 className="text-xl font-semibold mb-3">Remaining quota</h2><div className="grid md:grid-cols-3 gap-4">{Object.entries(data.quota.remaining).map(([unit, remaining]) => <Card key={unit} title={unit} value={String(remaining)} detail={`${data.quota.used[unit]} used · projected ${data.projectedPeriodEnd[unit]}`} />)}</div></section>
    <section className="grid md:grid-cols-2 gap-6 mt-8"><Panel title="API keys"><button onClick={() => void createKey()} className="text-indigo-300 text-sm mb-3">+ Create key</button>{data.apiKeys.map(k => <p key={k.id} className="font-mono text-sm py-2 border-t border-gray-800">{k.name} · {k.prefix}… {k.revokedAt ? 'revoked' : 'active'}</p>)}</Panel><Panel title="Notifications"><p className="text-gray-400 text-sm">Warnings are sent at {data.notificationThresholds.join('%, ')}% utilization. Configure thresholds with <code>PUT /v1/notifications</code>.</p></Panel><Panel title="Invoices">{data.invoices.length ? data.invoices.map(i => <p key={i.id} className="text-sm py-2 border-t border-gray-800">{i.id} · ${(i.amountCents / 100).toFixed(2)} · {i.status}</p>) : <p className="text-gray-400 text-sm">No invoices yet.</p>}</Panel><Panel title="Upgrade"><p className="text-gray-400 text-sm mb-3">Checkout does not change access. A durable entitlement webhook does.</p><button onClick={() => void upgrade('operator')} className="rounded bg-indigo-500 px-3 py-2 text-sm">Upgrade to Operator</button></Panel></section></>}
  </div></main>
}
function Card({ title, value, detail }: { title: string; value: string; detail: string }) { return <div className="rounded-xl border border-gray-800 bg-gray-900 p-5"><p style={{ fontFamily: MONO }} className="text-xs uppercase text-gray-500">{title}</p><p className="text-2xl font-semibold mt-2">{value}</p><p className="text-sm text-gray-400 mt-2">{detail}</p></div> }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border border-gray-800 bg-gray-900 p-5"><h2 className="font-semibold mb-3">{title}</h2>{children}</section> }
