#!/usr/bin/env python3
"""Bind the existing Coq lane to reviewed sources and explicit declarations.

The committed target manifest is an input, never regenerated by CI. Whole-source
hashes freeze statements and local definitions; Check queries test the explicitly
listed exports. This is same-job build evidence, not a new mathematical authority
or an independent kernel replay. Shared-library/OS trust remains outside scope.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
from pathlib import Path, PurePosixPath

COMPILE_FLAGS = ["-q", "-async-proofs", "off"]
QUERY_FLAGS = ["-q", "-quiet", "-batch", "-l"]


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sealed(value: dict) -> dict:
    body = dict(value)
    body.pop("sha256", None)
    raw = json.dumps(body, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return {**body, "sha256": digest(raw.encode("utf-8"))}


def read_sealed(path: Path) -> dict:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict) or sealed(value) != value:
        raise ValueError(f"invalid content digest: {path}")
    return value


def validate_contract(contract: dict) -> None:
    if (contract.get("kind") != "COQ_BUILD_CONTRACT_V1" or sealed(contract) != contract
            or contract.get("compile_flags") != COMPILE_FLAGS
            or contract.get("query_flags") != QUERY_FLAGS
            or contract.get("binding_scope") != "SOURCE_BYTES_AND_EXPLICIT_DECLARATIONS"
            or not re.fullmatch(r"[0-9a-f]{40}", contract.get("source_commit", ""))
            or not re.fullmatch(r"[0-9a-f]{64}", contract.get("targets_sha256", ""))):
        raise ValueError("invalid build contract")
    identity = contract.get("verifier_identity", {})
    executables = identity.get("executables", {})
    if set(executables) != {"coqc", "coqtop"}:
        raise ValueError("missing verifier identity")
    for name, item in executables.items():
        if (not re.fullmatch(r"[0-9a-f]{64}", item.get("sha256", ""))
                or not item.get("version", "").strip()
                or not Path(item.get("path", "")).is_absolute()):
            raise ValueError(f"invalid verifier identity: {name}")
    dependencies = identity.get("compiled_dependencies", {})
    if not dependencies or any(not re.fullmatch(r"[0-9a-f]{64}", sha) for sha in dependencies.values()):
        raise ValueError("missing/invalid compiled dependency identity")


def validate_targets(formal_root: Path, manifest: dict) -> dict:
    if manifest.get("kind") != "COQ_TARGET_MANIFEST_V1":
        raise ValueError("unsupported target manifest")
    files = manifest.get("files", {})
    actual = {p.relative_to(formal_root).as_posix() for p in formal_root.rglob("*.v")}
    if not files or set(files) != actual:
        raise ValueError("target/source file inventory mismatch")
    for relative, entry in files.items():
        path = PurePosixPath(relative)
        if path.is_absolute() or ".." in path.parts or path.suffix != ".v":
            raise ValueError(f"unsafe target path: {relative}")
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", path.stem):
            raise ValueError(f"unsupported module name: {relative}")
        source = formal_root / relative
        if source.is_symlink() or digest(source.read_bytes()) != entry["source_sha256"]:
            raise ValueError(f"frozen source mismatch: {relative}")
        names = entry["declarations"]
        if not isinstance(names, list) or len(names) != len(set(names)):
            raise ValueError(f"duplicate/invalid declarations: {relative}")
        if any(not isinstance(n, str) or not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_']*", n) for n in names):
            raise ValueError(f"unsafe declaration name: {relative}")
    return files


def run_text(argv: list[str], *, cwd: Path | None = None) -> str:
    result = subprocess.run(argv, cwd=cwd, capture_output=True, text=True,
                            encoding="utf-8", timeout=120, check=True)
    return result.stdout


def verifier_identity() -> dict:
    executables = {}
    for name in ("coqc", "coqtop"):
        found = shutil.which(name)
        if found is None:
            raise ValueError(f"missing verifier: {name}")
        path = Path(found).resolve(strict=True)
        executables[name] = {"path": str(path), "sha256": digest(path.read_bytes()),
                             "version": run_text([str(path), "--version"]).strip()}
    library = Path(run_text([executables["coqc"]["path"], "-where"]).strip()).resolve(strict=True)
    # Bind the installed compiled Coq libraries and plugins, not just a version
    # label. This does not attest all transitive native runtime dependencies.
    dependencies = {
        p.relative_to(library).as_posix(): digest(p.read_bytes())
        for p in sorted(library.rglob("*"))
        if p.is_file() and p.suffix in {".vo", ".vos", ".cmxs", ".cma"}
    }
    if not dependencies:
        raise ValueError("no compiled Coq library dependencies found")
    return {"executables": executables, "library_root": str(library),
            "compiled_dependencies": dependencies,
            "assumption_semantics": "VERSION_BOUND_NOT_REGRESSION_CHARACTERIZED",
            "native_runtime_dependencies": "NOT_FULLY_ATTESTED"}


def freeze(formal_root: Path, target_path: Path, source_commit: str) -> dict:
    if not re.fullmatch(r"[0-9a-f]{40}", source_commit):
        raise ValueError("source_commit must be an exact Git SHA-1")
    raw = target_path.read_bytes()
    manifest = json.loads(raw)
    validate_targets(formal_root, manifest)
    # Existing artifacts cannot serve as evidence for this build. A fresh
    # checkout is already required by the workflow; fail instead of reusing.
    if any(p.suffix in {".vo", ".vos", ".vok", ".glob"} for p in formal_root.rglob("*")):
        raise ValueError("stale compiled artifacts exist before the build")
    return sealed({"kind": "COQ_BUILD_CONTRACT_V1", "source_commit": source_commit,
                   "targets_sha256": digest(raw), "targets": manifest,
                   "verifier_identity": verifier_identity(),
                   "compile_flags": COMPILE_FLAGS,
                   "query_flags": QUERY_FLAGS,
                   "binding_scope": "SOURCE_BYTES_AND_EXPLICIT_DECLARATIONS"})


def declaration_query(relative: str, names: list[str]) -> str:
    module = PurePosixPath(relative).stem
    return ("Set Coqtop Exit On Error.\n" + f"Require Import {module}.\n"
            + "".join(f"Check {module}.{name}.\n" for name in names))


def check(formal_root: Path, target_path: Path, contract: dict,
          evidence_root: Path) -> dict:
    validate_contract(contract)
    if digest(target_path.read_bytes()) != contract["targets_sha256"]:
        raise ValueError("reviewed target manifest changed after freeze")
    files = validate_targets(formal_root, contract["targets"])
    if verifier_identity() != contract["verifier_identity"]:
        raise ValueError("verifier or compiled dependencies changed after freeze")
    evidence_root.mkdir(parents=True, exist_ok=True)
    records = {}
    for relative, entry in sorted(files.items()):
        source = formal_root / relative
        safe = relative.replace("/", "__").removesuffix(".v")
        query = (evidence_root / f"{safe}.v").resolve()
        query_text = declaration_query(relative, entry["declarations"])
        # Keep the query and output for replay; do not put generated sources
        # inside formal_root, whose exact file set is part of the contract.
        query.write_text(query_text, encoding="utf-8")
        vo, glob = source.with_suffix(".vo"), source.with_suffix(".glob")
        if not vo.is_file() or not glob.is_file() or vo.is_symlink() or glob.is_symlink():
            raise ValueError(f"missing/invalid compiled artifacts: {relative}")
        vo_digest, glob_digest = digest(vo.read_bytes()), digest(glob.read_bytes())
        argv = [contract["verifier_identity"]["executables"]["coqtop"]["path"],
                *contract["query_flags"], str(query)]
        result = subprocess.run(argv, cwd=source.parent, stdout=subprocess.PIPE,
                                stderr=subprocess.STDOUT, timeout=120, check=False)
        (evidence_root / f"{safe}.log").write_bytes(result.stdout)
        if result.returncode != 0:
            raise ValueError(f"declaration query failed: {relative} (exit {result.returncode})")
        if digest(vo.read_bytes()) != vo_digest or digest(glob.read_bytes()) != glob_digest:
            raise ValueError(f"compiled artifact changed during query: {relative}")
        records[relative] = {"source_sha256": entry["source_sha256"],
                             "declarations": entry["declarations"], "query_exit_code": 0,
                             "query_sha256": digest(query_text.encode("utf-8")),
                             "query_log_sha256": digest(result.stdout),
                             "vo_sha256": vo_digest, "glob_sha256": glob_digest}
    validate_targets(formal_root, contract["targets"])
    if digest(target_path.read_bytes()) != contract["targets_sha256"]:
        raise ValueError("target manifest changed during queries")
    for relative, record in records.items():
        for suffix, key in ((".vo", "vo_sha256"), (".glob", "glob_sha256")):
            if digest((formal_root / relative).with_suffix(suffix).read_bytes()) != record[key]:
                raise ValueError(f"compiled artifact changed during queries: {relative}")
    if verifier_identity() != contract["verifier_identity"]:
        raise ValueError("verifier or compiled dependencies changed during queries")
    return sealed({"kind": "COQ_BUILD_BINDING_V1", "status": "VERIFIED",
                   "contract": contract, "files": records,
                   "independence": "SAME_JOB", "kernel_replay": "NOT_PERFORMED",
                   "production": "NOT_ADMITTED"})


def verify_receipt_binding(binding: dict, formal_root: Path, source_commit: str) -> None:
    """Join recorded build evidence to receipt sources outside the Coq container.

    This validates the local content-addressed join, not the honesty of the host
    that generated it. The producer workflow remains part of the trust boundary.
    """
    if (sealed(binding) != binding or binding.get("kind") != "COQ_BUILD_BINDING_V1"
            or binding.get("status") != "VERIFIED"):
        raise ValueError("invalid or failed build binding")
    contract = binding["contract"]
    validate_contract(contract)
    if contract["source_commit"] != source_commit:
        raise ValueError("contract/receipt source commit mismatch")
    targets = validate_targets(formal_root, contract["targets"])
    if set(binding["files"]) != set(targets):
        raise ValueError("declaration evidence file inventory mismatch")
    for relative, target in targets.items():
        record = binding["files"][relative]
        if (record["source_sha256"] != target["source_sha256"]
                or record["declarations"] != target["declarations"]
                or type(record["query_exit_code"]) is not int or record["query_exit_code"] != 0):
            raise ValueError(f"declaration evidence mismatch: {relative}")
        if record["query_sha256"] != digest(declaration_query(relative, target["declarations"]).encode("utf-8")):
            raise ValueError(f"declaration query digest mismatch: {relative}")
        for key in ("vo_sha256", "glob_sha256", "query_sha256", "query_log_sha256"):
            if not re.fullmatch(r"[0-9a-f]{64}", record[key]):
                raise ValueError(f"invalid artifact digest: {relative}/{key}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("freeze", "check"))
    parser.add_argument("--formal-root", required=True, type=Path)
    parser.add_argument("--targets", required=True, type=Path)
    parser.add_argument("--source-commit")
    parser.add_argument("--contract", required=True, type=Path)
    parser.add_argument("--out", type=Path)
    args = parser.parse_args()
    try:
        if args.mode == "freeze":
            value = freeze(args.formal_root, args.targets, args.source_commit or "")
            destination = args.contract
        else:
            if args.out is None:
                parser.error("check requires --out")
            destination = args.out
            value = check(args.formal_root, args.targets, read_sealed(args.contract),
                          destination.parent / "declarations")
        # Do not silently overwrite a prior run or refreeze a changed target.
        with destination.open("x", encoding="utf-8") as out:
            json.dump(value, out, indent=2, sort_keys=True, ensure_ascii=False)
            out.write("\n")
    except (ValueError, OSError, KeyError, TypeError, subprocess.SubprocessError) as exc:
        parser.exit(1, f"Coq build binding failed: {exc}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
