#!/usr/bin/env python3
"""Canonical hosted replay for the finite φ spectral-inertia diagnostic.

This command freezes a modest, CI-friendly finite section so that the observed
Gram-normalized inertia table is generated by code rather than copied into a
status document.  The result is T1 numerical evidence only.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from harness.sdk.weil_spectral_inertia_probe import (
    SpectralProbeConfig,
    WeilSpectralInertiaProbe,
    build_scale_controls,
)


CANONICAL_CONFIG = SpectralProbeConfig(
    tau=2.0,
    p_cutoff=100,
    k_basis_dim=4,
    n_quad=2048,
    t_bound=50.0,
    max_prime_shift=None,
    zero_tolerance=1e-10,
    negative_tolerance=1e-8,
)


def build_canonical_payload() -> dict[str, Any]:
    probe = WeilSpectralInertiaProbe(CANONICAL_CONFIG)
    payload = probe.run_scale_probe(build_scale_controls())
    payload.update(
        {
            "probe_id": "PHI_SPECTRAL_INERTIA_CANONICAL_V1",
            "liminf_proven": False,
            "phi_specificity_established": False,
            "original_user_table_reproduced": False,
            "global_weil_positivity_proven": False,
            "rh_proven": False,
        }
    )
    return payload


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    payload = build_canonical_payload()
    path = Path(args.output)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
