#!/usr/bin/env python3
"""Offline source/config contract for the Claude 5.5 deployment migration."""
from __future__ import annotations

import json
import re
from pathlib import Path
from unittest import TestCase, main

ROOT = Path(__file__).resolve().parents[3]


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


class Anthropic55DeploymentContractTests(TestCase):
    def test_direct_api_deployments_pin_55(self) -> None:
        expectations = {
            "vertex/serve.py": 'AEGIS_DEFAULT_MODEL", "claude-opus-5-5"',
            "vertex/cloudbuild.yaml": "AEGIS_DEFAULT_MODEL=claude-opus-5-5",
            "worker-src/index.ts": "model: 'claude-opus-5-5'",
            "render.yaml": "value: claude-opus-5-5",
            "agents/run.sh": "AEGIS_DEFAULT_MODEL:-claude-opus-5-5",
            "agents/register_managed.py": 'AEGIS_DEFAULT_MODEL", "claude-opus-5-5"',
            "agents/agents.yaml": "default_model: claude-opus-5-5",
            "genomics/interpret.py": 'model: str = "claude-opus-5-5"',
            "genomics/interpret_demo.py": '"AEGIS_SWARM_MODEL", "claude-opus-5-5"',
        }
        for path, needle in expectations.items():
            with self.subTest(path=path):
                self.assertIn(needle, read(path))

        bridge = read("sovereign-omega-v2/python/bridge.py")
        self.assertGreaterEqual(
            bridge.count("data.get('model', 'claude-opus-5-5')"),
            2,
        )

    def test_opus_55_gateway_rejects_legacy_sampling_parameters(self) -> None:
        source = read("vertex/serve.py")
        self.assertIn("CLAUDE_5_5_UNSUPPORTED_PARAMETER", source)
        self.assertIn('"temperature"', source)
        self.assertIn('"top_p"', source)
        self.assertIn('"top_k"', source)

    def test_current_managed_agent_and_coordinator_ids_use_sonnet_55(self) -> None:
        self.assertIn(
            "model: 'claude-sonnet-5-5'",
            read("sovereign-omega-v2/src/api/managed-agent-client.ts"),
        )
        coordinator = read("sovereign-omega-v2/src/constitutional/coordinator.ts")
        self.assertNotIn("claude-sonnet-4-6", coordinator)
        self.assertGreaterEqual(coordinator.count("claude-sonnet-5-5"), 4)

    def test_cockpit_vertex_uses_55_capable_sdk_and_eu_multiregion(self) -> None:
        pkg = json.loads(read("cockpit/server/package.json"))
        vertex = pkg["dependencies"]["@anthropic-ai/vertex-sdk"]
        version = tuple(int(x) for x in re.findall(r"\d+", vertex)[:3])
        self.assertGreaterEqual(version, (0, 20, 0))

        lock = json.loads(read("cockpit/server/package-lock.json"))
        locked = lock["packages"]["node_modules/@anthropic-ai/vertex-sdk"]["version"]
        locked_version = tuple(int(x) for x in locked.split(".")[:3])
        self.assertGreaterEqual(locked_version, (0, 20, 0))

        server = read("cockpit/server/src/index.ts")
        self.assertIn("process.env.GOOGLE_CLOUD_REGION ?? 'eu'", server)
        self.assertIn("process.env.CLAUDE_MODEL      ?? 'claude-sonnet-5-5'", server)

        build = read("cockpit/cloudbuild.yaml")
        self.assertIn("GOOGLE_CLOUD_REGION=eu", build)
        self.assertIn("CLAUDE_MODEL=claude-sonnet-5-5", build)

    def test_generated_terraform_drift_is_explicitly_not_silently_rewritten(self) -> None:
        terraform = read("terraform/main.tf")
        self.assertIn("This file is autogenerated. Do not edit this file directly.", terraform)
        self.assertIn('"AEGIS_DEFAULT_MODEL" = "claude-opus-4-8"', terraform)


if __name__ == "__main__":
    main()
