import { useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, BookOpen, Check, Clock3, ExternalLink, Menu, Play, Search, Sparkles, Users, X } from 'lucide-react'

type Lesson={id:number;title:string;description:string;duration:string;category:string;color:string}
const lessons:Lesson[]=[
{id:1,title:'Get started with ChatGPT Enterprise',description:'Learn the essentials, explore your workspace, and see how ChatGPT can support your day-to-day work.',duration:'6 min',category:'Getting started',color:'#d8edff'},
{id:2,title:'Set up your Enterprise workspace',description:'Configure workspace settings, invite your team, and give everyone a secure place to collaborate.',duration:'8 min',category:'For admins',color:'#e5e0ff'},
{id:3,title:'Manage members and permissions',description:'Add members, assign roles, and manage access so your organization can work confidently.',duration:'7 min',category:'For admins',color:'#ffe2d8'},
{id:4,title:'Protect your company data',description:'Understand privacy, security, data controls, and the enterprise protections built into ChatGPT.',duration:'5 min',category:'Security',color:'#d9f2e5'},
{id:5,title:'Create and share custom GPTs',description:'Build tailored GPTs with your organization’s knowledge and share them across your workspace.',duration:'9 min',category:'Using ChatGPT',color:'#fff0c7'},
{id:6,title:'Bring ChatGPT into your workflow',description:'Discover practical ways to draft, analyze, brainstorm, and turn ideas into outcomes faster.',duration:'7 min',category:'Using ChatGPT',color:'#d9eeee'},
]
function Logo(){return <span className="logo"><b>✣</b><strong>OpenAI</strong></span>}
function Card({lesson,done,open}:{lesson:Lesson;done:boolean;open:()=>void}){return <article className="card" tabIndex={0} onClick={open} onKeyDown={e=>e.key==='Enter'&&open()}><div className="art" style={{background:lesson.color}}><div className="window"><i/><div><b>✦</b><span/><span/><span/></div></div><button aria-label="Play lesson"><Play size={17} fill="currentColor"/></button>{done&&<em><Check size={13}/> Complete</em>}</div><div className="card-copy"><small><span>{lesson.category}</span><span><Clock3 size={13}/>{lesson.duration}</span></small><h3>{lesson.title}</h3><p>{lesson.description}</p><strong>Start lesson <ArrowRight size={15}/></strong></div></article>}
export function App(){
 const [search,setSearch]=useState(false),[query,setQuery]=useState(''),[menu,setMenu]=useState(false),[active,setActive]=useState<Lesson|null>(null),[done,setDone]=useState<number[]>([])
 const shown=useMemo(()=>lessons.filter(x=>(x.title+x.description+x.category).toLowerCase().includes(query.toLowerCase())),[query])
 const complete=(x:Lesson)=>{setDone(d=>d.includes(x.id)?d:[...d,x.id]);setActive(null)}
 return <div>
 <header><a href="#top" className="brand"><Logo/><i/>Academy</a><nav className={menu?'open':''}><a href="#lessons">Learning paths</a><a href="#resources">Resources</a><a href="#community">Community</a></nav><div className="actions">{search?<label className="search"><Search size={16}/><input autoFocus placeholder="Search lessons" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={()=>{setSearch(false);setQuery('')}}><X size={16}/></button></label>:<button className="plain" onClick={()=>setSearch(true)}><Search size={20}/></button>}<button className="login">Log in</button><button className="hamb" onClick={()=>setMenu(!menu)}><Menu/></button></div></header>
 <main id="top"><section className="hero"><a href="#lessons" className="back"><ArrowLeft size={15}/> All use cases</a><div className="hero-grid"><div className="hero-copy"><span className="kicker"><Sparkles size={14}/> CHATGPT ENTERPRISE</span><h1>Set up and start using<br/>ChatGPT Enterprise</h1><p>Everything you need to confidently launch ChatGPT Enterprise and help your team get more done.</p><a href="#lessons" className="primary">Start learning <ArrowRight size={17}/></a></div><div className="visual"><div className="bubble one"/><div className="bubble two"/><div className="panel backpanel">Workspace<i/><i/><i/></div><div className="panel frontpanel"><span>✣ &nbsp; ChatGPT Enterprise</span><h4>How can I help your team today?</h4><div>Message ChatGPT <ArrowRight size={14}/></div></div></div></div><div className="stats"><div><BookOpen/><span><b>6 lessons</b>Step-by-step guidance</span></div><div><Clock3/><span><b>About 45 minutes</b>Learn at your own pace</span></div><div><Users/><span><b>Built for every team</b>Admins and members</span></div></div></section>
 <section id="lessons" className="lessons"><div className="title-row"><div><small>LEARNING PATH</small><h2>Start with the essentials</h2><p>Follow the path in order, or jump to the lesson that matters most to you.</p></div><div className="progress"><span>{done.length} of {lessons.length} complete</span><i><b style={{width:`${done.length/lessons.length*100}%`}}/></i></div></div>{query&&<p className="result">{shown.length} results for “{query}”</p>}<div className="grid">{shown.map(x=><Card key={x.id} lesson={x} done={done.includes(x.id)} open={()=>setActive(x)}/>)}</div>{!shown.length&&<div className="empty"><Search/><h3>No lessons found</h3><p>Try a different search term.</p></div>}</section>
 <section className="cta" id="resources"><div><small>READY FOR MORE?</small><h2>Build new habits with ChatGPT</h2><p>Explore practical prompts and resources designed to help every role do their best work.</p></div><button>Browse all resources <ExternalLink size={16}/></button></section></main>
 <footer><Logo/><span>© 2026 OpenAI</span><div><a href="#privacy">Privacy</a><a href="#terms">Terms</a><a href="#help">Help center</a></div></footer>
 {active&&<div className="overlay" onMouseDown={()=>setActive(null)}><section className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setActive(null)}><X/></button><div className="video" style={{background:active.color}}><span><Play fill="currentColor"/></span></div><small>{active.category} · {active.duration}</small><h2>{active.title}</h2><p>{active.description}</p><button className="primary" onClick={()=>complete(active)}>{done.includes(active.id)?'Review complete':'Mark as complete'} <Check size={17}/></button></section></div>}
 </div>
}
