/**
 * AEGIS Cross-Product Proof Ledger
 *
 * Minting authority is EXTERNAL to the inference system.
 * The caller generates a nonce BEFORE the inference runs — this nonce is
 * embedded in the token, proving an outside party was present and attesting.
 * The system produces audit records but cannot complete a mint without a
 * caller_nonce it did not generate. Self-serving minting is structurally
 * impossible: token_id = hash(chain_hash || caller_nonce) requires both.
 *
 * Constitutional invariant: AdaptivePower(T) ≤ ReplayVerifiability(T)
 * A system that mints its own currency violates this — the token would certify
 * more than it can replay-verify. The caller_nonce is the external anchor.
 */

import type { ConstitutionalAuditRecord, BackendType } from './constitutional-ai.js'

export type ProductId = 'platform-picker' | 'hook-generator' | 'content-calendar' | 'cockpit'

export interface ProofToken {
  readonly token_id: string       // hash(chain_hash || caller_nonce) — requires both parties
  readonly caller_nonce: string   // generated by caller before inference — external anchor
  readonly product: ProductId
  readonly call_id: string
  readonly prompt_hash: string
  readonly backend: BackendType
  readonly ccil_valid: boolean
  readonly session_index: number
  readonly minted_at: number
  readonly latency_ms: number
}

export interface LedgerStats {
  total: number
  ccil_valid: number
  ccil_ratio: number
  by_product: Record<string, number>
  by_backend: Record<string, number>
  chain_tip: string
}

const LEDGER_KEY = 'aegis_proof_ledger_v2'  // v2: caller_nonce required
const MAX_TOKENS = 500

async function sha256hex(input: string): Promise<string> {
  const data = new TextEncoder().encode(input)
  const buf = await crypto.subtle.digest('SHA-256', data)
  return Array.from(new Uint8Array(buf))
    .map(b => b.toString(16).padStart(2, '0'))
    .join('')
}

/**
 * Generate a caller nonce — MUST be called before callConstitutional.
 * The nonce commits the caller to this inference before seeing the result.
 */
export function generateCallerNonce(): string {
  const bytes = new Uint8Array(32)
  crypto.getRandomValues(bytes)
  return Array.from(bytes).map(b => b.toString(16).padStart(2, '0')).join('')
}

function readLedger(): ProofToken[] {
  try {
    const raw = typeof localStorage !== 'undefined' ? localStorage.getItem(LEDGER_KEY) : null
    return raw ? (JSON.parse(raw) as ProofToken[]) : []
  } catch {
    return []
  }
}

function writeLedger(tokens: ProofToken[]): void {
  try {
    if (typeof localStorage !== 'undefined') {
      localStorage.setItem(LEDGER_KEY, JSON.stringify(tokens))
    }
  } catch {
    try {
      localStorage.setItem(LEDGER_KEY, JSON.stringify(tokens.slice(-Math.floor(MAX_TOKENS / 2))))
    } catch { /* silent */ }
  }
}

/**
 * Mint a proof token. Called by the product UI after receiving a result —
 * NOT by callConstitutional itself. The caller_nonce must have been generated
 * before the inference ran, proving the caller was present before the result
 * was known. Without a pre-committed nonce, the token cannot be formed.
 */
export async function mintToken(
  record: ConstitutionalAuditRecord,
  product: ProductId,
  caller_nonce: string,
): Promise<ProofToken> {
  if (!caller_nonce || caller_nonce.length < 16) {
    throw new Error('mintToken requires a caller_nonce generated before inference')
  }

  // token_id requires both the system's chain_hash AND the caller's nonce
  const token_id = await sha256hex(record.chain_hash + '\x00' + caller_nonce)

  const token: ProofToken = Object.freeze({
    token_id,
    caller_nonce,
    product,
    call_id: record.call_id,
    prompt_hash: record.prompt_hash,
    backend: record.backend,
    ccil_valid: record.ccil_valid,
    session_index: record.session_index,
    minted_at: record.timestamp_ms,
    latency_ms: record.latency_ms,
  })

  const ledger = readLedger()
  ledger.push(token)
  writeLedger(ledger.length > MAX_TOKENS ? ledger.slice(-MAX_TOKENS) : ledger)

  return token
}

export function getLedger(): ProofToken[] {
  return readLedger()
}

export function getLedgerStats(): LedgerStats {
  const tokens = readLedger()
  const by_product: Record<string, number> = {}
  const by_backend: Record<string, number> = {}
  let ccil_valid = 0

  for (const t of tokens) {
    by_product[t.product] = (by_product[t.product] ?? 0) + 1
    by_backend[t.backend] = (by_backend[t.backend] ?? 0) + 1
    if (t.ccil_valid) ccil_valid++
  }

  return {
    total: tokens.length,
    ccil_valid,
    ccil_ratio: tokens.length > 0 ? ccil_valid / tokens.length : 0,
    by_product,
    by_backend,
    chain_tip: tokens.length > 0 ? tokens[tokens.length - 1].token_id : 'genesis',
  }
}

export function clearLedger(): void {
  try {
    if (typeof localStorage !== 'undefined') localStorage.removeItem(LEDGER_KEY)
  } catch { /* silent */ }
}
