-- AEGIS Sovereign Provider Mesh runtime observation registry V1.
-- Stores provider state/evidence hashes only. No credentials, tokens, account IDs,
-- promo codes, or raw external responses belong in this table.
-- authority_effect = NONE

begin;

create table if not exists public.provider_runtime_observations_v1 (
  id bigint generated by default as identity primary key,
  provider_id text not null check (provider_id ~ '^[a-z0-9][a-z0-9._-]{1,63}$'),
  plane text not null check (plane in ('EXECUTION','INTELLIGENCE','CONTROL')),
  observation_state text not null check (
    observation_state in (
      'UNKNOWN',
      'ACCOUNT_CONFIGURED',
      'NETWORK_REACHABLE',
      'CREDENTIAL_MISSING',
      'OBSERVED_AVAILABLE',
      'OBSERVED_UNAVAILABLE',
      'BILLING_BLOCKED'
    )
  ),
  capabilities text[] not null default '{}',
  blocker_code text,
  evidence_kind text not null,
  evidence_hash text not null check (evidence_hash ~ '^[0-9a-f]{64}$'),
  authority_effect text not null default 'NONE' check (authority_effect = 'NONE'),
  observed_at timestamptz not null default now(),
  expires_at timestamptz
);

alter table public.provider_runtime_observations_v1 enable row level security;

drop policy if exists "deny_client_access_service_only"
  on public.provider_runtime_observations_v1;

create policy "deny_client_access_service_only"
  on public.provider_runtime_observations_v1
  as restrictive
  for all
  to anon, authenticated
  using (false)
  with check (false);

comment on policy "deny_client_access_service_only"
  on public.provider_runtime_observations_v1 is
  'AEGIS service-only posture: anon and authenticated are explicitly denied; service_role retains BYPASSRLS access.';

revoke all on table public.provider_runtime_observations_v1 from anon, authenticated;

create index if not exists provider_runtime_observations_v1_provider_time_idx
  on public.provider_runtime_observations_v1 (provider_id, observed_at desc);

create or replace view public.provider_runtime_latest_v1
with (security_invoker = true)
as
select distinct on (provider_id)
  provider_id,
  plane,
  observation_state,
  capabilities,
  blocker_code,
  evidence_kind,
  evidence_hash,
  authority_effect,
  observed_at,
  expires_at,
  case
    when expires_at is null then false
    when expires_at <= now() then true
    else false
  end as is_expired
from public.provider_runtime_observations_v1
order by provider_id, observed_at desc, id desc;

revoke all on public.provider_runtime_latest_v1 from anon, authenticated;

commit;
