-- AEGIS Sovereign Provider Mesh selection receipts V1.
-- Every valid runtime selection or no-provider denial is bound to the current
-- provider evidence snapshot. authority_effect = NONE.

begin;

create table if not exists public.provider_selection_receipts_v1 (
  id bigint generated by default as identity primary key,
  capability text not null,
  outcome text not null check (outcome in ('SELECTED','DENIED')),
  provider_id text,
  provider_evidence_hash text check (
    provider_evidence_hash is null or provider_evidence_hash ~ '^[0-9a-f]{64}$'
  ),
  denial_code text,
  runtime_snapshot_root text not null check (
    runtime_snapshot_root ~ '^[0-9a-f]{64}$'
  ),
  authority_effect text not null default 'NONE' check (authority_effect = 'NONE'),
  selected_at timestamptz not null,
  receipt_hash text not null unique check (receipt_hash ~ '^[0-9a-f]{64}$')
);

alter table public.provider_selection_receipts_v1 enable row level security;

drop policy if exists "deny_client_access_service_only"
  on public.provider_selection_receipts_v1;

create policy "deny_client_access_service_only"
  on public.provider_selection_receipts_v1
  as restrictive
  for all
  to anon, authenticated
  using (false)
  with check (false);

revoke all on table public.provider_selection_receipts_v1 from anon, authenticated;

create index if not exists provider_selection_receipts_v1_time_idx
  on public.provider_selection_receipts_v1 (selected_at desc);

create or replace function public.provider_runtime_snapshot_root_v1()
returns text
language sql
stable
set search_path = ''
as $$
  select encode(
    extensions.digest(
      convert_to(
        coalesce(
          string_agg(
            concat_ws(
              '|',
              provider_id,
              plane,
              observation_state,
              array_to_string(capabilities, ','),
              coalesce(blocker_code, ''),
              evidence_kind,
              evidence_hash,
              to_char(observed_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),
              coalesce(
                to_char(expires_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),
                ''
              ),
              authority_effect
            ),
            E'\n' order by provider_id
          ),
          ''
        ),
        'UTF8'
      ),
      'sha256'
    ),
    'hex'
  )
  from public.provider_runtime_latest_v1;
$$;

revoke all on function public.provider_runtime_snapshot_root_v1()
  from public, anon, authenticated;
grant execute on function public.provider_runtime_snapshot_root_v1()
  to service_role;

create or replace function public.record_provider_selection_v1(
  p_capability text,
  p_outcome text,
  p_provider_id text,
  p_provider_evidence_hash text,
  p_denial_code text
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_snapshot_root text;
  v_selected_at timestamptz := clock_timestamp();
  v_selected_at_text text;
  v_receipt_hash text;
begin
  if p_outcome not in ('SELECTED','DENIED') then
    raise exception 'invalid provider selection outcome';
  end if;

  if p_outcome = 'SELECTED' then
    if p_provider_id is null or p_provider_evidence_hash is null then
      raise exception 'selected provider receipt requires provider evidence';
    end if;
    if p_provider_evidence_hash !~ '^[0-9a-f]{64}$' then
      raise exception 'invalid provider evidence hash';
    end if;
    if p_denial_code is not null then
      raise exception 'selected provider receipt cannot contain denial code';
    end if;
  else
    if p_provider_id is not null or p_provider_evidence_hash is not null then
      raise exception 'denied provider receipt cannot bind provider evidence';
    end if;
    if p_denial_code is null or btrim(p_denial_code) = '' then
      raise exception 'denied provider receipt requires denial code';
    end if;
  end if;

  v_snapshot_root := public.provider_runtime_snapshot_root_v1();
  v_selected_at_text := to_char(
    v_selected_at at time zone 'UTC',
    'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'
  );

  v_receipt_hash := encode(
    extensions.digest(
      convert_to(
        concat_ws(
          '|',
          'AEGIS_PROVIDER_SELECTION_RECEIPT_V1',
          p_capability,
          p_outcome,
          coalesce(p_provider_id, ''),
          coalesce(p_provider_evidence_hash, ''),
          coalesce(p_denial_code, ''),
          v_snapshot_root,
          v_selected_at_text,
          'NONE'
        ),
        'UTF8'
      ),
      'sha256'
    ),
    'hex'
  );

  insert into public.provider_selection_receipts_v1(
    capability,
    outcome,
    provider_id,
    provider_evidence_hash,
    denial_code,
    runtime_snapshot_root,
    authority_effect,
    selected_at,
    receipt_hash
  ) values (
    p_capability,
    p_outcome,
    p_provider_id,
    p_provider_evidence_hash,
    p_denial_code,
    v_snapshot_root,
    'NONE',
    v_selected_at,
    v_receipt_hash
  );

  return v_receipt_hash;
end;
$$;

revoke all on function public.record_provider_selection_v1(text,text,text,text,text)
  from public, anon, authenticated;
grant execute on function public.record_provider_selection_v1(text,text,text,text,text)
  to service_role;

commit;
