-- AEGIS Sovereign Provider Mesh automatic probe scheduler V1.
-- Zero-touch refresh for non-billing probes only.
-- No model inference, no provider credentials, no paid workload.
-- authority_effect = NONE

begin;

create extension if not exists pg_cron with schema extensions;

create table if not exists public.provider_probe_requests_v1 (
  id bigint generated by default as identity primary key,
  request_id bigint not null unique,
  probe_kind text not null check (
    probe_kind in ('SUPABASE_EDGE_METHOD_PROBE','NEBIUS_NOAUTH_PROBE')
  ),
  provider_id text not null check (provider_id ~ '^[a-z0-9][a-z0-9._-]{1,63}$'),
  expected_status integer not null,
  created_at timestamptz not null default now(),
  processed_at timestamptz,
  response_status integer,
  response_hash text check (response_hash is null or response_hash ~ '^[0-9a-f]{64}$')
);

alter table public.provider_probe_requests_v1 enable row level security;

drop policy if exists "deny_client_access_service_only"
  on public.provider_probe_requests_v1;

create policy "deny_client_access_service_only"
  on public.provider_probe_requests_v1
  as restrictive
  for all
  to anon, authenticated
  using (false)
  with check (false);

revoke all on table public.provider_probe_requests_v1 from anon, authenticated;

create or replace function public.enqueue_provider_probes_v1()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  edge_request_id bigint;
  nebius_request_id bigint;
begin
  edge_request_id := net.http_get(
    url := 'https://rwehltdwpsncnwxzkwik.supabase.co/functions/v1/chat',
    params := '{}'::jsonb,
    headers := '{}'::jsonb,
    timeout_milliseconds := 10000
  );

  insert into public.provider_probe_requests_v1(
    request_id, probe_kind, provider_id, expected_status
  ) values (
    edge_request_id,
    'SUPABASE_EDGE_METHOD_PROBE',
    'supabase-edge',
    405
  );

  nebius_request_id := net.http_post(
    url := 'https://api.tokenfactory.nebius.com/v1/chat/completions',
    body := jsonb_build_object(
      'model','deepseek-ai/DeepSeek-R1-0528',
      'messages',jsonb_build_array(
        jsonb_build_object('role','user','content','AEGIS network canary')
      )
    ),
    params := '{}'::jsonb,
    headers := jsonb_build_object('Content-Type','application/json'),
    timeout_milliseconds := 10000
  );

  insert into public.provider_probe_requests_v1(
    request_id, probe_kind, provider_id, expected_status
  ) values (
    nebius_request_id,
    'NEBIUS_NOAUTH_PROBE',
    'nebius-token-factory',
    401
  );

  return jsonb_build_object(
    'edge_request_id', edge_request_id,
    'nebius_request_id', nebius_request_id,
    'authority_effect', 'NONE'
  );
end;
$$;

revoke all on function public.enqueue_provider_probes_v1()
  from public, anon, authenticated;
grant execute on function public.enqueue_provider_probes_v1()
  to service_role;

create or replace function public.process_provider_probe_responses_v1()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  rec record;
  evidence_payload text;
  evidence_hash text;
  processed_count integer := 0;
begin
  for rec in
    select
      q.id as queue_id,
      q.request_id,
      q.probe_kind,
      q.provider_id,
      q.expected_status,
      r.status_code,
      r.timed_out,
      r.error_msg
    from public.provider_probe_requests_v1 q
    join net._http_response r on r.id = q.request_id
    where q.processed_at is null
    order by q.id
  loop
    evidence_payload := concat_ws(
      '|',
      'AEGIS_PROVIDER_PROBE_RESPONSE_V1',
      rec.probe_kind,
      rec.provider_id,
      rec.request_id::text,
      coalesce(rec.status_code::text,'NULL'),
      coalesce(rec.timed_out::text,'NULL'),
      coalesce(rec.error_msg,'')
    );

    evidence_hash := encode(
      extensions.digest(convert_to(evidence_payload, 'UTF8'), 'sha256'),
      'hex'
    );

    if rec.probe_kind = 'SUPABASE_EDGE_METHOD_PROBE'
       and rec.status_code = 405
       and coalesce(rec.timed_out,false) = false then
      insert into public.provider_runtime_observations_v1(
        provider_id, plane, observation_state, capabilities,
        blocker_code, evidence_kind, evidence_hash, authority_effect, expires_at
      ) values (
        'supabase-edge',
        'EXECUTION',
        'OBSERVED_AVAILABLE',
        array['SERVERLESS_FUNCTION','DATABASE','HTTP_EGRESS'],
        null,
        'AUTO_EDGE_405_PROBE_V1',
        evidence_hash,
        'NONE',
        now() + interval '20 minutes'
      );

    elsif rec.probe_kind = 'NEBIUS_NOAUTH_PROBE'
       and rec.status_code = 401
       and coalesce(rec.timed_out,false) = false then
      insert into public.provider_runtime_observations_v1(
        provider_id, plane, observation_state, capabilities,
        blocker_code, evidence_kind, evidence_hash, authority_effect, expires_at
      ) values (
        'nebius-token-factory',
        'INTELLIGENCE',
        'NETWORK_REACHABLE',
        array['MODEL_INFERENCE'],
        'AUTH_NOT_PRESENT_IN_PROBE',
        'AUTO_NEBIUS_401_PROBE_V1',
        evidence_hash,
        'NONE',
        now() + interval '20 minutes'
      );
    end if;

    update public.provider_probe_requests_v1
    set processed_at = now(),
        response_status = rec.status_code,
        response_hash = evidence_hash
    where id = rec.queue_id;

    processed_count := processed_count + 1;
  end loop;

  return processed_count;
end;
$$;

revoke all on function public.process_provider_probe_responses_v1()
  from public, anon, authenticated;
grant execute on function public.process_provider_probe_responses_v1()
  to service_role;

do $$
declare
  job record;
begin
  for job in
    select jobid
    from cron.job
    where jobname in (
      'aegis-provider-probe-enqueue-v1',
      'aegis-provider-probe-process-v1'
    )
  loop
    perform cron.unschedule(job.jobid);
  end loop;
end
$$;

select cron.schedule(
  'aegis-provider-probe-enqueue-v1',
  '*/10 * * * *',
  'select public.enqueue_provider_probes_v1();'
);

select cron.schedule(
  'aegis-provider-probe-process-v1',
  '1-59/10 * * * *',
  'select public.process_provider_probe_responses_v1();'
);

commit;
