"""Projection layer — RFC 0001 §6.

Each projection ``P_lang : IR -> source`` is a pure function and introduces no
semantic meaning the IR does not already carry. Alongside ``render`` every
projection exposes ``readback`` which re-extracts a *coarse comparison schema*
from its own generated source. The coarse schema captures only what all three
target type systems can express simultaneously — structural nesting
(``list`` / ``option``), reference targets, and a leaf category in
``{string, bool, number, <RefName>}``. TypeScript and Python collapse every
numeric width to a single type, so ``number`` is the strongest honest
cross-language leaf invariant. The equivalence gate (§8) asserts the three
readbacks and the IR's expected coarse schema are identical.
"""

from __future__ import annotations

import re

from ..ir import IR, IRType

GENERATED_HEADER_LINES = (
    "AUTO-GENERATED by aegis-interface (RFC 0001). DO NOT EDIT.",
    "Source of truth: WIT interface definitions -> IR -> this projection.",
)


def snake_to_pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in name.split("_") if part)


def pascal_to_snake(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def fmt_number(value: float) -> str:
    """Deterministic float rendering for range doc comments."""
    if value == int(value):
        return f"{value:.1f}"
    return repr(value)


def range_comment_text(lo: float, hi: float) -> str:
    return f"range: {fmt_number(lo)}..={fmt_number(hi)}"


def coarse_type(t: IRType) -> str:
    """IR type -> coarse cross-language descriptor."""
    if t.kind == "primitive":
        if t.name == "string":
            return "string"
        if t.name == "bool":
            return "bool"
        return "number"
    if t.kind == "ref":
        return t.name
    if t.kind in ("list", "option"):
        return f"{t.kind}<{coarse_type(t.inner)}>"
    raise ValueError(f"un-coarsable type kind {t.kind!r}")


def expected_coarse_schema(ir: IR) -> dict:
    """The IR rendered into coarse comparison form — the gate's reference."""
    records = {
        rec.name: [
            {
                "name": f.name,
                "type": coarse_type(f.type),
                "range": [f.range.min, f.range.max] if f.range else None,
            }
            for f in rec.fields
        ]
        for rec in ir.records
    }
    variants = {var.name: list(var.cases) for var in ir.variants}
    return {"records": records, "variants": variants}


def parse_range_comment(text: str):
    """Extract ``[lo, hi]`` from a ``range: a..=b`` comment body, else None."""
    m = re.search(r"range:\s*([-\d.eE+]+)\.\.=([-\d.eE+]+)", text)
    if not m:
        return None
    return [float(m.group(1)), float(m.group(2))]
